### ISSUE TITLE
Vore bra med lite exempel så man kommer igång snabbare...

### ISSUE THREAD

**Issue by salgo60** [Riksarkivet/dataplattform#1]
**Önskan 1** Vore bra med mer Python/Notebook exempel för Arkiv

Skriver nu en [notebook](https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/blob/main/Notebook/Skolregistret%20Stockholms%20stadsarkiv.ipynb) som hämtar Stockholms stads skolregister och sedan kollar agent id hos Riksarkivet.... 

* körde [webscraping först](https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/blob/main/Notebook/Skolregistret%20Stockholms%20stadsarkiv.ipynb)
* såg sedan att ni har ett API med XML men gav upp.... tror många med mig gillar JSON api:er mer än XML

**Fråga 2**: finns enkelt sätt att få ut alla arkiv om skolor med metadata?  se GITHUB [issue 1](https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/issues/1) att ha Svenska skolor över tid som metadataset i [Bildhistoria](https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata) 

Exempel data Stockholms Stads skolregister hos Stadsarkivet har för 
* [Västertorpsskolan](https://sok.stadsarkivet.stockholm.se/Databas/skolregistret/Visa/vastertorpsskolan/1e8b447c-ae51-4fa2-96a2-19c60f05add9)
> Folkskola, Försöksskola, Inbyggd realskola 1955-1961, Enhetsskola 1959-1962 med åk 7-9, Grundskola åk 1-9 1962-1975, åk F-6 from ht 1975.
* arkiv 
  * [SSA/1846](https://sok.riksarkivet.se/?postid=ArkisRef%20SE/SSA/1846): Fruängens skola 1958-2013 --> agent [ZXgqFqKF8aYO0RzstHRkO6](https://sok.riksarkivet.se/arkiv/ZXgqFqKF8aYO0RzstHRkO6)
  * [SSA/0319B](https://sok.riksarkivet.se/?postid=ArkisRef%20SE/SSA/0319B): Västertorpssskolan 2002/03-2013. --> agent: [ifMneL7Lh4M0AcXJqz6Q00](https://sok.riksarkivet.se/arkiv/ifMneL7Lh4M0AcXJqz6Q00)
  
  
<img width="939" alt="image" src="https://user-images.githubusercontent.com/14206509/168754209-41ad0bba-4021-4753-82a9-7d2d14c61824.png">

  **känns logiskt** att det borde gå att söka ut allt data som kommer från kommuners olika skolregister hos er....
 
 I wikidata har vi idag samma struktur som Skolverket/SCB(om jag fattat rätt) dvs
 * Västertorpsskolan WD [Q89788826](https://www.wikidata.org/wiki/Q89788826) har del WD [Q89191100](https://www.wikidata.org/wiki/Q89191100) "Västertorpsskolan" som är en skolenhet med [skolenhetskod](https://www.wikidata.org/wiki/Property:P7894) = [92007673](http://api.scb.se/UF0109/v2/skolenhetsregister/sv/skolenhet/92007673)
   [graf](https://w.wiki/5AQk)
   
   
<img width="939" alt="image" src="https://user-images.githubusercontent.com/14206509/168454663-99e17862-795b-42c8-b94a-a35ec0087e8a.png">

* [www.scb.se Skolenhetsregistret](https://www.scb.se/lamna-uppgifter/undersokningar/Skolenhetsregistret/)

**Önskan 3** vore smidigt **om även Riksarkivet hade koppling till [SCB/Skolverkets Skolenhetsregister](https://www.scb.se/lamna-uppgifter/undersokningar/Skolenhetsregistret/)**

### Wikidata
* svenska skolprojekt finns idag 
** [Wikidata:WikiProject Sweden/Schools](https://www.wikidata.org/wiki/Wikidata:WikiProject_Sweden/Schools)

**Comment by salgo60** [comment]
**Email svar [Johannes Westberg ](https://www.rug.nl/staff/b.a.j.westberg/)professor of Theory and History of Education** WD [Q57470236](https://www.wikidata.org/wiki/Q57470236) [twitter](https://twitter.com/dr_jwestberg)

<img width="646" alt="image" src="https://user-images.githubusercontent.com/14206509/168552255-8d1d71aa-8c73-4692-ad99-40d9c6d52b19.png">


```
"Hej Magnus!

Ja det är ett ambitiöst projekt! Bra bakgrund till alla olika slags skolformer ges också i SCBs statistiska sammanställningar, 
se bifogat. En komplett översikt över läroverk och motsvarande från säg 1850-talet och framåt vore inte omöjligt - 
de är inte så många, och finns angivna efter stad i exempelvis SCBs serie P, se bif. fil.  
Folkskolorna (och underkategorier som småskolor, mindre folkskolor etc) är väl lite knepigare: 
de organiserades av Sveriges omkring 2,300 församlingar fram till 1900-talets början, och har ju 
funnits så väldigt många, och gick inte sällan under olika namn, så där torde just församlingsnamnet 
vara en rimlig ingång  om man vill bringa ordning i dem.

/Johannes "
```


[Elever_i_obligatoriska_skolor_1847-1962.pdf](https://github.com/Riksarkivet/dataplattform/files/8698421/Elever_i_obligatoriska_skolor_1847-1962.pdf)
[Elever-i-skolor-for-yrkesutbildning-1844-1970.pdf](https://github.com/Riksarkivet/dataplattform/files/8698422/Elever-i-skolor-for-yrkesutbildning-1844-1970.pdf)
[Elever-i-icke-obligatoriska-skolor-1864-1970.pdf](https://github.com/Riksarkivet/dataplattform/files/8698423/Elever-i-icke-obligatoriska-skolor-1864-1970.pdf)
[BISOS 1851-1917_BISOS P Undervisningsväsendet 1868-1911_BISOS P Allmänna läroverken 1876-1911_Undervisningsvasendet-P-Allmanna-laroverken-lasaret-1890-1891.pdf](https://github.com/Riksarkivet/dataplattform/files/8698425/BISOS.1851-1917_BISOS.P.Undervisningsvasendet.1868-1911_BISOS.P.Allmanna.laroverken.1876-1911_Undervisningsvasendet-P-Allmanna-laroverken-lasaret-1890-1891.pdf)

**Comment by salgo60** [comment]
* se även liknande [fråga till Bebyggelseregistret](https://www.wikidata.org/wiki/Wikidata_talk:WikiProject_Sweden/Schools#Bebyggelseregistret_skolor)

<img width="766" alt="image" src="https://user-images.githubusercontent.com/14206509/168991641-3b6f315b-40ea-4f3f-b6df-ddd09bd12812.png">

**Comment by nilsw-ra** [comment]
Det var flera frågor på en gång, jag ska försöka besvara dem i separata kommentarer för att underlätta eventuella uppföljningsfrågor.

1. Fler exempel

Det är avsikten att fylla på med fler exempel. Kom gärna med förslag på vad de skall behandla för att underlätta förståelse för och användning av APIerna.

OAI-PMH är ett gammalt standardprotokoll för ett specifikt syfte (masshämtning av metadata till portaler och aggregatorer). Vi använder det fär att leverera data till Archives Portal Europe och Nuohtti för närvarande. I och med att det är en tjänst som vi har sedan tidigare är det motiverat att göra den publikt tillgänglig och dokumenterad, även om protokollet i sig kan ses som något gammalmodigt. Det finns idag inga indikationer om att OAI-PMH skall uppdateras eller ersättas med något som kan leverera API-svar i JSON-format.

Riksarkivet planerar att ta fram ett sök-API med funktonalitet som motsvarar i första hand [fritextsökningen i söktjänsten](https://sok.riksarkivet.se/?Sok=true). Tanken för närvarande är att sökresultatet kommer att presenteras i JSON-format, med länkar till enskilda poster i form av derefererbara RDF-URIer så att utvecklare som använder APIet kan välja att hämta data i JSON-LD eller RDF/XML.

**Comment by nilsw-ra** [comment]
2. Söka skolarkiv

OAI-PMH har ingen sökfunktion och vi har ingen ämnesbaserad IIIF collection för just skolarkiv (det saknas i allmänhet scannat material). Vi kan ta fram en IIIF collection för detta ändamål ändå, för att ge en maskinläsbar lista, med innehåll i stil med

`{
   "id": "https://lbiiif.riksarkivet.se/collection/arkiv/Bmy5hW5gbwF376eC4B2jT1",
   "type": "Collection",
   "label": {
      "sv": [
         "Enskede skola"
      ]
   },
   "summary": {
      "sv": [
         "Referenskod: SE/SSA/2456",
         "Arkivinstitution: Stockholms stadsarkiv",
         "Datering: 1991-2013"
      ]
   }
}`

Referenskoden kan sedan nyttjas för att hämta metadata om arkivet med OAI-PMH. Detta är dock inte generellt möjligt för närvarande, då kommunala arkiv i NAD inte är tillgängliga via OAI-PMH. Arbete pågår med att uppdatera villkoren för data i NAD så att vi kan ge åtkomst till de arkiv som dataleverantören vill göra publika.

När det gäller sökning i söktjänsten, och i förlängningen i ett sök-API, så finns det inga strukturerade dataelement som anger att ett arkiv är just ett skolarkiv. Så tyvärr är i nuläget enda möjligheten [fritextsökning på "skola", med facetturval Typ: Arkiv och Arkivbildare / upphov: Kommunal myndighet](https://sok.riksarkivet.se/?Sokord=skola&EndastDigitaliserat=false&AvanceradSok=False&FacettFilter=arkis_ark_typ_facet%24Arkiv%3A%7Carkis_aukt_huvudkategori_facet%24Kommunal+myndighet%3A&FacettState=gG8Klw%3Ao%7CAURkng%3Ac%7C&page=1&f=True#tab).

**Comment by salgo60** [comment]
Tack min inkompetens gäller XML 😳 så där behöver jag stöd gissar att vi är flera ;-) plus som jag antyder hur kan man dra nytta av NAD för att hitta [Sveriges skolor över tid](https://www.wikidata.org/wiki/Wikidata:WikiProject_Sweden/Schools) vilket idag inte verkar finnas samlat som ett dataset

Ett sätt att dra nytta av GITHUB är att ni sätter [ett eller flera topics](https://github.com/topics) på era Repositories så kan andra som skapa lösningar med ert API och sätta samma [GITHUB topics](https://github.com/topics)
* jag skapade en egenskap i WD för detta [Property:P9100](https://www.wikidata.org/wiki/Property:P9100)
  * tog mig friheten och satte detta på NAD WD [Q10594823](https://www.wikidata.org/wiki/Q10594823#P9100) - [topics/nationellaarkivdatabasen](https://github.com/topics/nationellaarkivdatabasen)
  * kom gärna med bättre topics (och/eller uppdatera WD själv) - jag skrev lite om denna WD egenskap se [github.community](https://github.community/t/wikidata-property-p9100-created-for-github-topics/158508)

**Comment by nilsw-ra** [comment]
Vad gäller att tolka OAI-PMH-XML så finns ett litet exempel som jag gjorde häromdagen, men inte hunnit dokumentera än, [för att ta reda på persistent id för en arkivenhet utifrån referenskoden](https://github.com/Riksarkivet/dataplattform/blob/main/docs/examples/common/refcode_to_pid.py).

Jag ska se till att ta fram ett mer omfattande exempel!

**Comment by nilsw-ra** [comment]
3. Koppling till SCB:s skolenhetsregister

Kopplingar till andra system generellt är ett intressant område, som tyvärr mestadels saknas i våra data. I fallet skolarkiv borde arkiven egentligen ha en koppling till en organisations-auktoritet i vår databas, som in sin tur borde ha referenser till SCB och eventuella kommunala register.

Båda dessa är antagligen rätt enkla att utveckla, men det är betydligt mer krävande att komplettera befintliga data med dessa kopplingar då det kräver en manuell insats. Som alltid är det en fråga om prioriteringar, jag kan ta med önskemålet, men inte göra några utfästelser om eller när det kan bli verklighet.

**Comment by nilsw-ra** [comment]
> Ett sätt att dra nytta av GITHUB är att ni sätter [ett eller flera topics](https://github.com/topics) på era Repositories så kan andra som skapa lösningar med ert API och sätta samma [GITHUB topics](https://github.com/topics)

Tack för tipset! Jag har uppdaterat repots About med ett par topics.

**Comment by salgo60** [comment]
Spännande just om skolor skickade vi en fråga till Johannes [länk](https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/issues/1#issuecomment-1127392047) där verkar det vara lite High Chaparall så alla tips mottages

```
"Hej Magnus!

Ja det är ett ambitiöst projekt! Bra bakgrund till alla olika slags skolformer ges också i SCBs statistiska sammanställningar, 
se bifogat. En komplett översikt över läroverk och motsvarande från säg 1850-talet och framåt vore inte omöjligt - 
de är inte så många, och finns angivna efter stad i exempelvis SCBs serie P, se bif. fil.  
Folkskolorna (och underkategorier som småskolor, mindre folkskolor etc) är väl lite knepigare: 
de organiserades av Sveriges omkring 2,300 församlingar fram till 1900-talets början, och har ju 
funnits så väldigt många, och gick inte sällan under olika namn, så där torde just församlingsnamnet 
vara en rimlig ingång  om man vill bringa ordning i dem.

/Johannes "
```

NAD id
* vi har i WD både gamla och nya och är väldigt intresserad att komplettera det lilla vi har idag och kanske kan ni dra nytta av WD med alla dess fel och brister... jag har länge föreslagit att ni [som Arkiv Digital hämtar kartdata från WD](https://phabricator.wikimedia.org/T199907) för kyrkböckerna...
  
  * [Property:P5324](https://www.wikidata.org/wiki/Property:P5324) - [lista](https://w.wiki/5BGU) / [karta](https://w.wiki/5BGB) / [externa egenskaper på dessa objekt](https://w.wiki/5BGM)
  * [Property:P9713](https://www.wikidata.org/wiki/Property:P9713) - [lista](https://w.wiki/5BGY)/ [karta](https://w.wiki/5BFV) / [externa egenskaper](https://w.wiki/5BGQ) 
  
För skolor där vi nu startar från 0 vore det enormt snyggt att ha NAD som en bas för vårt data dvs. att Skola identifierad i WD skall ha NAD koppling.... --> att ni förhoppningvis kan utnyttja artiklar och annan data som finns för ex. flickskolor - [artikel](https://sv.wikipedia.org/wiki/Flickskola) / Wiki [Kategori:Flickskolor_i_Sverige](https://sv.wikipedia.org/wiki/Kategori:Flickskolor_i_Sverige)  

`Båda dessa är antagligen rätt enkla att utveckla, men det är betydligt mer krävande att komplettera befintliga data med dessa kopplingar då det kräver en manuell insats. ` 

Japp och där kanske WD och [Bildhistoria](https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata) och andra aktörer kan bidraga... WD med sin öppenhet är ju perfekt för detta problemet är att hitta en bra struktur och eldsjälar.... Bildhistoria bygger på [SPA](https://portrattarkiv.se/about) som jag haft enorm nytta med då jag förbättra data på Sveriges Riksdagsmän se [issues/38](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/38) som används av forskare som gör om Riksdagstrycket till [TEI format](https://clarin-eric.github.io/parla-clarin/) och har [WD Qnummer som identifierare för en riksdagsman](https://github.com/welfare-state-analytics/riksdagen-corpus/issues/39)...

**Comment by salgo60** [comment]
> När det gäller sökning i söktjänsten, och i förlängningen i ett sök-API, så finns det inga strukturerade dataelement som anger att ett arkiv är just ett skolarkiv. Så tyvärr är i nuläget enda möjligheten [fritextsökning på "skola", med facetturval Typ: Arkiv och Arkivbildare / upphov: Kommunal myndighet](https://sok.riksarkivet.se/?Sokord=skola&EndastDigitaliserat=false&AvanceradSok=False&FacettFilter=arkis_ark_typ_facet%24Arkiv%3A%7Carkis_aukt_huvudkategori_facet%24Kommunal+myndighet%3A&FacettState=gG8Klw%3Ao%7CAURkng%3Ac%7C&page=1&f=True#tab).

**enormt snyggt** :rocket: kanske en yngre hjärna med riktiga Python kunskaper kan göra stordåd av detta 
cc: @miroli

Kanske  @Abbe98 skulle kunna trolla fram skolbyggnader hur bebyggelseregistret... 
[tweet](https://twitter.com/salgo60/status/1526941096483475457)

**Comment by salgo60** [comment]
OT: Man borde ha ett ämne på repositoriet att det är ett Riksarkiv... se [video tanke](https://youtu.be/-M8HU88J2Ig)
* jag satte på WD [Q2122214](https://www.wikidata.org/w/index.php?title=Q2122214&diff=prev&oldid=1642030831) - [nationalarchive](https://github.com/topics/nationalarchive)
* i videon "hoppar jag runt" med plug-in [Entity Explosion](https://www.wikidata.org/wiki/Wikidata:Entity_Explosion) som rekommenderas
   * jag ser framför mig att då vi har alla Sveriges skolor över tid kan vi med Entity Explosion hoppa mellan Wikipedia artikeln, NAD, Bebyggelseregistret, [Bildhistoria](https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata).... ungefär det vi kan göra med alla Sveriges riksdagspersoner i första, andra kammaren efter att https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/38 är färdig....
   
 SPARQL [Nationella arkiv enl. WD](https://w.wiki/5BNi) vore coolt om alla dela kod på GITHUB
 
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/14206509/169194735-e64e994b-b489-433c-bf97-3e1727c1ca47.png">

**Comment by nilsw-ra** [comment]
> OT: Man borde ha ett ämne på repositoriet att det är ett Riksarkiv...

Bra tanke, har lagt till det!

**Comment by salgo60** [comment]
**Pandas/Notebooks exempel** 

OT2 såg att pandas sedan 1.3.0 har [XML stöd](https://pandas.pydata.org/docs/reference/api/pandas.read_xml.html) så snart kanske undertecknad kan massera ert data ;-)  kan vara ett exempel på bra exempel att ha i er dokumentation jag brukar lyfta [SPARQL till pandas dataframe](https://phabricator.wikimedia.org/T257117) och sedan jobba vidare... med XML verkar det som man skall ha koll på olika namespace som vore bra om det framgick i exempel hur man sätter upp det...
* även ha [kod exempel i Notebooks](https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/blob/main/Notebook/Skolregistret%20Stockholms%20stadsarkiv.ipynb) underlättar

**Comment by nilsw-ra** [comment]
Nu finns ett lite större exempel på hur man kan läsa ut data från EAD-XML i OAI-PMH-svaren. https://github.com/Riksarkivet/dataplattform/blob/main/docs/examples/oai-pmh/read_archive.py

**Comment by salgo60** [comment]
Tackar frågan hur gör vi detta enklare att hitta för alla andra... kanske DIGG @MariaDahlgren eller Jonas Södergren @jonassodergren har tankar.... borde finnas en typ kulturhub på GITHUB där alla "drakarna" finns 😄 

Med digitaliseringen så måste vi börja knyta ihop data med data.... gissar att vi hittar massa "skit" som är soppat under mattan när man kopplar ihop saker som "skolor i Sverige" men det är ju dumt att alla gör samma misstag...

**Comment by salgo60** [comment]
Gärna länka till exemplen dvs. er leverabel (eng. [deliverables](https://blog.logrocket.com/product-management/what-are-deliverables-in-agile-why-do-we-have-them/)) för denna issue
