### ISSUE TITLE
Status: öppen och fri digital arkivinformation i två steg

### ISSUE THREAD

**Issue by salgo60** [Riksarkivet/dataplattform#12]
Ni skrev 2017

> Riksarkivet planerar att genomföra förändringen mot öppen och fri digital arkivinformation i två steg. Först tas abonnemangsavgiften till den digitala forskarsalen bort. I ett andra steg görs informationen tillgänglig som öppen, länkbar och maskinläsbar data.
> - Den blir då en del av den växande mängden öppna data från offentlig sektor. Min förhoppning är att innovatörer tar chansen och skapar bra produkter för medborgarna, säger Karin Åström Iko

* är detta levererat eller vad är planerat och hur och kommer det att finnas API:er till detta data?
   * [Karin Åström Iko pratar om visioner - Digikult 2018](https://youtu.be/Jf3pCElhxW8?t=1411) där det pratas om att saker skall sitta ihop se även #11

Även denna [tweet apr 9 2021](https://twitter.com/DavidHaskiya/status/1380490175080497164?s=20&t=G-fHfIfsJF0p1Q14mggB_A) ger intryck av att planer finns

<img width="709" alt="image" src="https://user-images.githubusercontent.com/14206509/215329221-a2d88bf5-fa89-4dd1-96ff-af9f9d82618f.png">

**Detta kom upp** för att vi på [Wikidata funderare över att skilja dödsplats och var en person är skriven från varandra](https://sv.wikipedia.org/wiki/Wikipedia:Wikidatafr%C3%A5gor#%C3%85tskilja_d%C3%B6dshemort_och_d%C3%B6dsort?) - idag geggar vi ihop det på wikidata. Min tro är att skulle Riksarkivet ha varje kyrkbok som öppen länkad data med ett API som har metadata 
* persistent identifierare - borde fungera bra med NAD plus bokens Bokstav och nummer
* tidsperiod
* församling
* typ av kyrkbok: dödbok, födelsebok, vigselbok, husförslängd....
* NAD
* antal bildsidor
* url
  * iiif
* digitaliserad - boolean
   * datum digitaliserad
* [Tora identifierare](https://www.wikidata.org/wiki/Property:P4820)

så kan det vara källa till dödsorten och vi kan ur källorna se var personen var skriven på ett tydligare sätt.... Idag kanske vi kan från den textsträng vi har se NAD och BILD id rel enkelt men länkade data är att föredra alla dagar i veckan - se nedan

Status idag:
* idag länkar vi i bästa fall till URL:en för sidan dödboken med referensen som en textsträng dvs. vi har inga persistenta identifierare som egen egenskap. Fanns en koppling från Bildid (persistent identifierare för sida gissar jag men en bild kan scannas om och gissar jag får då ett nytt id... så gör Arkiv Digital) till vilken kyrkbok som bilden finns i skulle vi kunna se att personen fanns vid sin död i Husförhörslängd och/eller dödbok för en viss församling... --> Se [SPARQL för personer begravda på Norra Begravningsplatsen med en källa dödsboken](https://w.wiki/6Gnx) / [karta](https://w.wiki/6GYJ) - endast det [med transkribering](https://w.wiki/6HHa) - samma men [gravar med koordinat och dödbok i hela Sverige i Wikidata](https://w.wiki/6Jft) / [enbart Riksdagsmän](https://w.wiki/6M2Y) / [enbart Riksdagsmän beskrivna av SBL](https://query.wikidata.org/embed.html#%23title%3A%20Map%20Deathbooks%20sources%20for%20people%20who%20are%20buried%20at%20a%20cemetery%20in%20Sweden%20and%20are%20a%20Swedish%20PM%20and%20documented%20in%20SBL%0A%23defaultView%3AMap%0Aselect%20%20%3Fperson%20%3FpersonLabel%20%3FstatedinLabel%20%3Ftitel%20%3FrefUrl%20%3Fcoord%20%3Fgraveplot%20%3Fgravestone%20%3Fimg%20%3Fcite%20%3FSBL%0A%7B%0A%20%20%20hint%3AQuery%20hint%3Aoptimizer%20%22None%22%20.%0A%20%20%20%3Fcem%20wdt%3AP17%20wd%3AQ34.%0A%20%20%20%3Fperson%20wdt%3AP119%20%3Fcem.%20%23Place%20of%20burial%0A%20%20%20%3Fperson%20p%3AP119%20%3FGraveStatement.%20%0A%20%20%20VALUES%20%3Fmember%20%7B%0A%20%20%20%20wd%3AQ33071890%20%0A%20%20%20%20wd%3AQ81531912%20%0A%20%20%20%20wd%3AQ82697153%20%0A%20%20%20%20wd%3AQ10655178%20%0A%20%20%7D%0A%20%20%3Fperson%20wdt%3AP3217%20%3FSBLid.%0A%20%20BIND%28URI%28CONCAT%28%22https%3A%2F%2Fsok.riksarkivet.se%2Fsbl%2FPresentation.aspx%3Fid%3D%22%2C%3FSBLid%29%29%20AS%20%3FSBL%29%0A%20%20%3Fperson%20wdt%3AP39%20%3Fmember%3B%0A%20%20%20%20OPTIONAL%20%7B%3FGraveStatement%20pq%3AP965%20%3Fgraveplot%7D%20%0A%09OPTIONAL%20%7B%3FGraveStatement%20pq%3AP625%20%3Fcoord%7D%20%0A%20%20%20%3Fperson%20%3Fprop%20%3Fstatement.%20%23all%20props%0A%20%20%20%7B%3Fstatement%20prov%3AwasDerivedFrom%20%3Fref%7D%0A%20%20%20OPTIONAL%20%7B%3Fref%20pr%3AP854%20%3FrefUrl%7D%20%0A%20%20%20OPTIONAL%20%7B%3Fref%20pr%3AP1476%20%3Ftitel%7D%20%0A%20%20%20OPTIONAL%20%7B%3Fref%20pr%3AP1683%20%3Fcite%7D%20%0A%20%20%20%7B%20%3Fref%20pr%3AP248%20wd%3AQ10478639%7D%0A%20%20%20%23FILTER%20%28CONTAINS%28str%28%3FNationalArchivesOfSweden%29%2C%27riksarkivet%27%29%29%20.%20%20%0A%20%20%20%3Fproperty%20wikibase%3Aclaim%20%3Fprop%20.%0A%20%20%20OPTIONAL%20%7B%3Fperson%20wdt%3AP18%20%3Fimg%7D%0A%20%20%20OPTIONAL%20%7B%3Fperson%20wdt%3AP1442%20%3Fgravestone%7D%0A%0A%20%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%2Csv%22%7D%0A%7D%0AGroup%20by%20%3Fperson%20%3FpersonLabel%20%3FstatedinLabel%20%20%3Ftitel%20%3FrefUrl%20%3Fgraveplot%20%3Fcoord%20%3Fgravestone%20%3Fimg%20%3Fcite%20%3FSBL%0A%0A)

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/14206509/215328607-ac484111-1be5-47dc-a12c-24e0dab9bcb2.png">

[<img width="842" alt="image" src="https://user-images.githubusercontent.com/14206509/215512606-5f535fcc-af14-4200-90ba-2ca7df246916.png">](https://w.wiki/6GYJ)

Exempel wd:[Q6229552](https://www.wikidata.org/wiki/Q6229552) A. A. Waldenström har som källa _Storkyrkoförsamlingens kyrkoarkiv, Död- och begravningsböcker, huvudserie, SE/SSA/0016/F I a/9 (1875-1894), bildid: 00007276_00277, sida 275_ --> 
* NAD SE/SSA/0016 --> Wikidata [haswbstatement:"P5324=SE/SSA/0016"](https://www.wikidata.org/wiki/Special:Search?fulltext=S%C3%B6k+efter+%27SE%2FRA%2F730226%27&fulltext=Search&search=haswbstatement%3A%22P5324%3DSE%2FSSA%2F0016%22&ns0=1&ns120=1) --> [WD Q43549106](https://www.wikidata.org/wiki/Q43549106) _"Storkyrkoförsamlingen"_

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/14206509/215328699-f1168a90-fa04-4d2e-9892-d0691b40ebc9.png">

* Församlingarna uppfattar jag har persistenta identifierare med NAD (eller [Tora identifierare](https://www.wikidata.org/wiki/Property:P4820))
* men vi saknar idag API till detta data?!?!? och API där vi kan hämta bildid: 00007276 och få koppling till NAD/församling

### Vem har kopplingar till en viss kyrkobok och sida

När RAÄ anordnade en workshop om IIIF pratade jag med Riksarkivets Olof Karsvall om en tanke att man skulle kunna se på en kyrkbok vilka externa som länkar en viss sida dvs. ungefär det som Wikidata gör med [Scholia](https://www.wikidata.org/wiki/Wikidata:Scholia) och [citation graphs](https://en.wikipedia.org/wiki/Citation_graph) , anledning att [citation graphs](https://en.wikipedia.org/wiki/Citation_graph) fungerar är just användandet av persistenta identifierare som [DOI](https://en.wikipedia.org/wiki/Digital_object_identifier) och [ORCID](https://en.wikipedia.org/wiki/ORCID) dvs, samma tänk bör finnas med kyrkböcker och min tro är att dom stora vinnare då skulle förutom släktforskare även vara kriminaltekniker se ["SILOS -> Kunskapsdatabaser för släktforskning ett hjälpmedel för att matcha DNA segment med person"](http://minancestry.blogspot.com/2020/06/kunskapsdatabaser-for-slaktforskning.html) (ett mycket starkare argument en den bandtyp som lyftes fram i en [DN debatt artikel om varför kulturarvet skall ha pengar 2021 jan 4](https://web.archive.org/web/20210106104744/https://www.dn.se/debatt/digitalisera-kulturarvet-for-demokratins-skull/))

> Där kunde oskyldigt utpekade personer rentvås tack vare att ett ålderstiget VHS-material fortfarande var spelbart och öppnade för en ny utredning

## Huvudfrågan förtydligad
men svara gärna på mina andra spekulationer/funderingar 

Riksarkivets dataplattform är det en del av öppen fri arkivinformation där öppen, länkbar och maskinläsbar data levereras för kyrkböckerna. Om ja finns detta levererat om ej levererat vad skall levereras och när? Har ni diskuterat detta med några andra externa som tänker sig implementera att koppla sig till kyrkböckerna som länkade data och har ni en dialog med Arkiv Digital som också levererar scannade kyrkböcker?

OT: Jag tror att skall forskarna börja jobba med kunskapsgrafer se "[Sveriges Riksdag 1867–2022: Ett ekosystem av länkad öppen data](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/84)" så skall även kopplingen till kyrkböcker vara länkade data. Har ni en dialog med dom eller andra?

OT2: era kyrkböcker finns idag på en IIIF plattform har jag förstått **finns det några exempel hur det används?** EN tanke jag hade var att ha transkriberingen av en del av kyrkboken i Wikidata och sedan kunna visa upp det som en IIIF annotering se [tweet 2019](https://twitter.com/salgo60/status/1134011455483895808?s=20&t=KTwcDDe8VKr5N7wBPn2BxA)

[<img width="709" alt="image" src="https://user-images.githubusercontent.com/14206509/215419918-b5badb4f-e7f3-40e7-89e3-1ba25057c9bd.png">](https://twitter.com/salgo60/status/1134011455483895808?s=20&t=KTwcDDe8VKr5N7wBPn2BxA)

OT 3: Jag gjorde ett gigg 2018 med Arkiv DIgital och kyrkböcker - [T199907](https://phabricator.wikimedia.org/T199907) / [FB](https://www.facebook.com/arkivdigital/posts/3000089753350216) så dom har använt Wikidata för att placera [kyrkböckerna på en karta "Ett helt nytt satt att navigera i arkivdigital"](https://www.arkivdigital.se/blog/nyheter-2/ett-helt-nytt-satt-att-navigera-i-arkivdigital/)
* Annan variant med Family Search 2018 [T200515](https://phabricator.wikimedia.org/T200515) där wikidata används som en hub med vertktyget [tools.wmflabs.org/hub](https://tools.wmflabs.org/hub/)

**Comment by salgo60** [comment]
Önskvärt är att metadata om enskilda kyrkböcker innehåller om dom finns tillgängliga elektroniskt och att det finns en change stream som kan läsas och se senaste ändringar jmf [Wikidata](https://www.wikidata.org/w/api.php?action=query&list=recentchanges) / [API:RecentChanges](https://www.mediawiki.org/wiki/API:RecentChanges) / [codepen.io](https://codepen.io/ottomata/pen/VKNyEw/) / app [rcvis](https://wikidata-todo.toolforge.org/rcvis.html)

**User Case**:  som släktforskare vill jag snabbt kunna se om en dödsbok släppts tillgänglig digitalt och vem i mitt släktträd det kan påverka
**Fördel**; data driven släktforskning dvs. mitt släktforskarprogram kan se att en person som dör 10 november 1957 i [ [Umeå stadsförsamling wd:Q18334316](https://www.wikidata.org/wiki/Q18334316) --> NAD [SE/HLA/1010220](https://sok.riksarkivet.se/?postid=ArkisRef%20SE/HLA/1010220) --> bör finnas i bok F5 --> **jag vill enkelt kunna se när den finns släppt i mitt släktforskarprogram**

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/14206509/215940206-4f0118ee-f6df-464f-befb-3b46824f5648.png">

* bra exempel på datadriven släktforskning är WikiTree och deras [data doctor projekt](https://www.wikitree.com/wiki/Project:Data_Doctors) se [beskrivning](https://www.wikidata.org/wiki/Wikidata_talk:Mismatch_Finder#WikiTree_WikiTree_person-ID_(P2949)_WikiTree+_and_the_WikiTree_Data_Doctors_Project) hur 33 miljoner profiler "synkroniseras" varje vecka mot Wikidata/FindAGrave och flera 100 olika regler se [beskrivning](https://www.wikidata.org/wiki/Wikidata_talk:Mismatch_Finder#WikiTree_WikiTree_person-ID_(P2949)_WikiTree+_and_the_WikiTree_Data_Doctors_Project) - [video](https://www.youtube.com/watch?v=pNehwVJWzKc)

[<img width="1227" alt="image" src="https://user-images.githubusercontent.com/14206509/215941169-fce991a2-bb6a-403c-a19d-bb13cee255c2.png">](https://www.youtube.com/watch?v=pNehwVJWzKc)

**Comment by nilsw-ra** [comment]
Det här repot är till för de APIer vi har i drift (OAI-PMH och IIIF) och kommande lösningar (sök-API), med issues för felrapporter, frågor etc som berör APIerna direkt. Jag stänger därför denna mer allmänt hållna issue, men ska självklart försöka svara kortfattat på åtminstone en del av frågorna i den.

"är detta levererat eller vad är planerat och hur och kommer det att finnas API:er till detta data?"

OAI-PMH och IIIF-APIerna är publikt tillgängliga sedan i våras. Vi arbetar med ett sök-API och länkad data-presentation av arkivenheter för närvarande. En första version kommer att bli tillgänglig under året.

"Även denna [tweet apr 9 2021](https://twitter.com/DavidHaskiya/status/1380490175080497164?s=20&t=G-fHfIfsJF0p1Q14mggB_A) ger intryck av att planer finns"

Det är mitt jobb det handlar om.

"Min tro är att skulle Riksarkivet ha varje kyrkbok som öppen länkad data med ett API som har metadata"

Publikt tillgängliga arkiv, serier, volymer etc kommer att få URIer

http://data.riksarkivet.se/arkiv/<pid>

t.ex. kommer volymen med födelse- och dopbok 1718-1744 för Borgviks socken

https://sok.riksarkivet.se/arkiv/v8buzQNrNIN2ecbLK5yjG0

att få URI

http://data.riksarkivet.se/arkiv/v8buzQNrNIN2ecbLK5yjG0

och ha en RDF-representation i två lager: dels grundläggande data i schema.org-format, dels mer komplett information i Records in Context-format.

MEN, även där de fysiska böckerna är scannade och bilderna publicerade är inte innehållet, t.ex. information om enskilda personer, digitaliserat. En del data om personer finns i födelse-, döds- och vigselregister, men detta täcker bara en liten del av det totala materialet och det finns inga referenser mellan registren (dvs man kan inte se om poster i de tre registren med samma personnamn handlar om samma person).

HTR-tolkning av de scannade böckerna är ett mycket intressant område, men är något som kommer att ta lång tid. Att sedan hitta och verifiera referenser, att göra riktiga länkade data av innehålet, är än mer omfattande och kommer inte att kunna ske med fullständig visshet.
