### ISSUE TITLE
Wikidata:Property proposal/National Archives of Sweden persistent identifier

### ISSUE THREAD

**Issue by salgo60** [Riksarkivet/dataplattform#13]
Some questions need to be answered in WD land [link](https://www.wikidata.org/wiki/Wikidata:Property_proposal/National_Archives_of_Sweden_persistent_identifier)
1) Do we need both [this Wikidata:Property_proposal/National_Archives_of_Sweden_persistent_identifier](https://www.wikidata.org/wiki/Wikidata:Property_proposal/National_Archives_of_Sweden_persistent_identifier) and [Property:P9713](https://www.wikidata.org/wiki/Property:P9713) "Swedish National Archive agent ID" fewer I guess is better
2) Is there an API or a list of the NAD available
3) Are Riksarkivets NAD mapped to Wikidata?
4) Do you have classified them so we understand if they are Notable for WD

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/14206509/227948816-193c9d12-8478-4377-bb54-b64e5c01c419.png">

**Comment by nilsw-ra** [comment]
This is a bit tricky as both archival objects, agents and concepts (e.g. topographic entities) have the same kind of persistent identifier. This id is a Base62-encoded UUID. So, P9713 is rather superfluous, I would prefer there to be one property for all these PIDs. BUT, things have moved since I wrote the proposal and I have realized that it would be better to use the RDF URIs for these objects (all three kinds). We don't serve RDF yet, but it is in the works now. For further complication, I thought we had landed in a URI pattern, but turns out there is one more issue to consider. The national archives of Finland are planning ti use URNs for PIDs, so question is if we should too. If we decide to do that, these URNs should also be used for RDF URIs rather than the http URIs I have considered so far:

http://data.riksarkivet/<object type>/<pid>

**Comment by salgo60** [comment]
Thanks keep us updated I guess most things are moving objects when we are trying to connect things....

Would be excellent if we could use Wikidata as a start as the project [Welfare state analýtics](https://github.com/welfare-state-analytics/riksdagen-corpus/issues/249#issuecomment-1485255102) are doing (they use students as [Emil](https://github.com/emla5688) and me to fix the data quality

My understanding is that they in the future **will be the trusted source to Wikidata** but as a step 1 WD is better than nothing....

**Comment by salgo60** [comment]
@nilsw-ra FYI changing the formatter URL in WD for a property is done in 2 secs [P1630](https://www.wikidata.org/wiki/Property:P1630)  and is [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) just changed in one place so dont that hesitate you
* my guess is that we will find much more difficult things when open the Pandoras jar of the National Archives 🚀 

[(![image](https://user-images.githubusercontent.com/14206509/228001147-66782fbb-6823-414f-8494-fee19008f905.png)](https://www.wikidata.org/wiki/Q6059617)

**Comment by nilsw-ra** [comment]
I see that the tentative URI scheme didn't com out as expected...

http://data.riksarkivet.se/{object type}/{pid}

e.g.

http://data.riksarkivet.se/agent/HX8UA8hDrH646m3GjpvwY3  (person authority record, Axel Munthe)
http://data.riksarkivet.se/archive/Tp1bCTomaKMVT0c9t1XLA0  (archive record, Axel Munthe's archive)

**Comment by salgo60** [comment]
Now I dont follow you did you change something in WD. Dont hesitate to call me 0735152802

Question is if its added value to have _type_ in the schema if you compare Wikidata we dont...

I guess persons are stable but archives are split and merged and maybe should have a more advanced model as part of, and  I guess parts of an archive can also be physical moved to other parts....

**Comment by nilsw-ra** [comment]
I have not done anything with the WikiData property proposal yet. I need to think this over in order to get something long term viable. I should probably put it on hold actually. All three kinds, archive data, person/organization authorities and concepts (including topographic entities) have persistent ids. (There is an unfortunate exception, but that is outside the scope of this). There is has part / is part of relation for archives and their subordinate elements which will be included in the RDF representation. E.g. Fonds (archive) -> Series -> Volume.

**Comment by salgo60** [comment]
ok 
* "unfortunate exception" we use redirects on mass in Wikidata see objects with NAD P5324 that has [merged the last 1000 days](https://w.wiki/6WAa) / [SBL P3217](https://w.wiki/6WAc)
  * people add new objects that are already there/ they add them in another language that some one later understand is the same object already in WD
  * **when I check Riksarkivets** August Strindbergs I feel you have **a lot of duplicates** that should be merged... maybe that is a bigger problem than the url schema...
    * [SE/GUB/2432](https://sok.riksarkivet.se/agent/pouIZiMDzI1DLJgQy0edF0) Strindberg, August  (1849 – 1912)
    * [SE/GUB/REA000053729](https://sok.riksarkivet.se/agent/Kyt91LXSmo70wzbi1uMJ00) STRINDBERG, AUGUST  (1849 – 1912)
    * [SE/UUB/REA000137171](https://sok.riksarkivet.se/agent/Rqrh1LdMwKUGvKty1yWfr7) STRINDBERG, JOHAN AUGUST (AUGUST)  (1849 – 1912)
    * [SE/LUB/722](https://sok.riksarkivet.se/agent/DoytrnzK5b2YfejOVMozoB) Strindberg, August  (1849 – 1912)
  * it looks like most of the data is [4 star data](https://5stardata.info/en/) with no external referencies (below dbpedia example) --> **to make the data useful it should be 5 star data**
  * some feedback [Riksarkivet SBL dataset](https://github.com/salgo60/Svenskaforsamlingar/issues/53) that is strings and not things
  
  <img width="1111" alt="image" src="https://user-images.githubusercontent.com/14206509/228440266-9ffc81b9-e296-4cfd-becf-93b9fb414409.png">
  
* would be cool if you archives started using Wikibase and delivered more trusted data than Wikidata....

---- 
interesting that [SE/LUB/722](https://sok.riksarkivet.se/agent/DoytrnzK5b2YfejOVMozoB) had same as dbpedia feels like Riksarkivet had some linked data ambitions that died...

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/14206509/228227698-28f4b657-72ce-4185-b62c-f6d99d3df92b.png">

**Comment by salgo60** [comment]
**OT** on the [friday session with Riksarkivet SBL](https://www.youtube.com/watch?v=ywFsLrn43N0) I asked them at [47 min](https://youtu.be/ywFsLrn43N0?t=2817) about if they were part of designing the future of the National Archives archive and they said no one asks them - maybe **use them as user cases** (see my thoughts of a [structured requirement process #25](https://github.com/salgo60/Svenskaforsamlingar/issues/25))
* my feeling is that they have extreme good domain knowledge and can be used the [lack of vision of delivering SBL I have written about in #6](https://github.com/salgo60/Svenskaforsamlingar/issues/6)
* I also think that we need to start to [work more together](https://github.com/salgo60/Svenskaforsamlingar/issues/25#issuecomment-1481067858) and create the digital data together see [thoughts](https://github.com/salgo60/Svenskaforsamlingar/issues/25#issuecomment-1481067858) and how WD now [works with Humlab](https://github.com/welfare-state-analytics/riksdagen-corpus/issues/249#issuecomment-1486736125)

**Comment by nilsw-ra** [comment]
I will get back on the issue on wikidata.org once we have decided what's best.

**Comment by salgo60** [comment]
Any [status](https://www.wikidata.org/wiki/Wikidata:Property_proposal/National_Archives_of_Sweden_persistent_identifier)?

**Comment by DavidHaskiya** [comment]
I'm afraid @nilsw-ra is no longer working at the Swedish National Archives. I will need to read-up myself and check with a colleague and get back to you all. Won't be until next week at the earliest since that colleague is on holiday this week.

**Comment by salgo60** [comment]
Sad I feel you moved in the right direction... I guess if he has left nothing will happen when he now has [Kultur IT](https://se.linkedin.com/in/nilsw) as "sponsor"....

* as I suggested before maybe we should have a meeting I can see now that @monirbounadi has some interesting thoughts about [Swedish Census 1930](https://www.wikidata.org/wiki/Q50798414) and how it maybe can be used to analyze how [people vote](https://github.com/welfare-state-analytics/riksdagen-corpus/issues/360#issuecomment-1727372376)  I feel he is inside Riksarkivet working with this project ["I demokratins namn – Kvinnorna som krävde rösträtt".](https://sok.riksarkivet.se/nyhetsarkiv?item=118837&sida=digitala-forskarsalen)
   * Questions I have
   * [ ] status API Swedish Census 1930
   * [ ] can we add **same as** Wikidata also on your side see how [DIGG is starting looking into persistent identifiers](https://github.com/diggsweden/persistent-identifiers-investigation/issues/13#issuecomment-1725792617) and I feel we need some kind of [observer pattern](https://refactoring.guru/design-patterns/observer) implemented --> we could start create who is citing this record in Census 1930... [compare citation graphs ](https://github.com/salgo60/DiggUptime/issues/85)we do today in [Wikidata](https://w.wiki/YF7) - more about [observe pattern and what I feel DIGG need to design](https://github.com/diggsweden/persistent-identifiers-investigation/issues/4#issuecomment-1727569593)
   
   ![image](https://github.com/Riksarkivet/dataplattform/assets/14206509/13e691fa-ea70-49d3-812e-89d6eb224501)   
   
   * [ ] do we need to change how WIkidata handle education or do something in Wikibase
   * [ ] ....
