### ISSUE TITLE
Folkräkningar (Sveriges befolkning) 1930 - forskningskvalitet på metadata?

### ISSUE THREAD

**Issue by salgo60** [Riksarkivet/dataplattform#14]
se [welfare-state-analytics/riksdagen-corpus/issues/243#issuecomment-1495777133](https://github.com/welfare-state-analytics/riksdagen-corpus/issues/243#issuecomment-1495777133)

Fråga:
1) Finns API till detta data - jag såg att [trackuback](https://trackuback.com/research) använder [Riksarkivet kyrkböcker via API ](https://www.rotter.se/senaste-nytt/3932-nu-lanseras-trackuback-2) var är bästa dokumentationen
   1) exempel kod?
   1) finns reconciliation stöd direkt från Open Refine
1) Finns kvaliten/värdemängder dokumenterade på exempelvis förmögenhet och skolutbildning
1) Är detta bästa platsen för att kommunicera med er om detta för projekt [welfare-state-analytics/riksdagen-corpus](https://github.com/welfare-state-analytics/riksdagen-corpus)?

**Comment by nilsw-ra** [comment]
Ska försöka svara på detta!

1. Planen är att folkräkningarna kommer att vara tillgängliga via det sök-API som är under utveckling, inklusive länkade data för de enskilda folkräkningsposterna  (Trackuback  använder OAI-PMH), dokumentation av sök-APIet, samt exempel, kommer att finnas i Wikin här på GitHub. Reconciliation-API är en tänkbar kommande utveckling, men inte specificierad och planerad.
2. Folkräkningsdata är huvudsakligen text, med samma datakvalitet som det analoga källmaterialet, uppgifter som skola och yrke är inte normaliserade och rekoncilierade mot någon kontrollerad vokabulär.
3. För frågor som berör användningen av våra APIer är det rätt plats. Om de som driver projektet vill diskutera andra frågor med Riksarkivet är det nog bäst att inleda per epost.

**Comment by salgo60** [comment]
Tack jag skall försöka lägga till kopplingar på Riksdagsgubbarna i Wikidata

Skrik till när det finns något att testa kanske vi skulle ha en WD egenskap för detta...

En fundering jag bollade med Projektet är att använda DOI --> WD har redan en egenskap och alla vet hur det fungerar.... något ni funderar på eller har redan...

**Comment by salgo60** [comment]
OT: [welfare-state-analytics/riksdagen-corpus](https://github.com/welfare-state-analytics/riksdagen-corpus/pull/258#issuecomment-1495631051) jobbar snyggt med testdriven approach så när data checkas in körs ett antal sanitetschecker som bl.a. hittade fel i Wikidata --> ett mönster som ni oldschool arkiv/myndigheter kanske kan ta efter - jag har länge [efterlyst metadataroundtripping](https://meta.wikimedia.org/wiki/Structured_data_for_GLAM-Wiki/Roundtripping/KMB) - se incheckning [v0.8.0](https://github.com/welfare-state-analytics/riksdagen-corpus/pull/258#issuecomment-1495631051) där dom har ett antal sanitets tester på data från Wikidata

[<img width="908" alt="image" src="https://user-images.githubusercontent.com/14206509/230021682-14d39219-4e8b-4a18-afc5-5fad19f6aede.png">](https://github.com/welfare-state-analytics/riksdagen-corpus/pull/258#issuecomment-1495631051)

[<img width="934" alt="image" src="https://user-images.githubusercontent.com/14206509/230053914-76a7a649-2cf6-4082-8036-64b65c3c72b3.png">](https://github.com/welfare-state-analytics/riksdagen-corpus/pull/258#issuecomment-1495698503)

### Update [Beteckningar undervisningsanstalter](https://sok.riksarkivet.se/folkrakningar?infosida=beteckningar-undervisningsanstalter)

cc: @fredrik1984

Skolbildning – Kolumn "15"
Nomenklatur för Skolbildning:

y = ingen uppgift alls.
x = ej läs- eller skrivkunnig.
0 = anteckning "ingen skola" eller liknande; ingen anteckning om läs- eller skrivkunnighet.
1 = ingen skola men läs- och skrivkunnig.
2 = endast läskunnig/ej skrivkunnig.
3 = småskola, folkskola.
4 = folkskolans påbyggnader; lägre specialutbildning.
5 = elementarutbildning eller högre specialutbildning utan avläggande av studentexamen.
7 = studentexamen utan efterföljande examen vid högre undervisningsanstalter.
8 = examen vid andra högre undervisningsanstalter än universitet och därmed jämställda högskolor.
9 = examen vid universitet och därmed jämställda skolor.

Då flera beteckningar kan komma i fråga, väljs den sannolika så vitt man kan bedöma av personens eget eller faderns yrke, sociala ställning m.m. I tveksamma fall samt i de fall att flera undervisningsanstalter bevistats väljes den högsta av de siffror som kan komma i fråga.

[Beteckningar undervisningsanstalter](https://sok.riksarkivet.se/folkrakningar?infosida=beteckningar-undervisningsanstalter)
[Mer om skolbildning](https://sok.riksarkivet.se/folkrakningar?infosida=mer-om-skolbildning)

<p style="margin: 0px 0px 10px; color: rgb(70, 70, 70); font-family: &quot;Open Sans&quot;, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Då fler beteckningar kunna ifrågakomma, väljes den sannolika, så vitt man kan bedöma av personens eget eller faderns yrke, sociala ställning m.m. I tveksamma fall samt i det fall att flera undervisningsanstalter bevistas väljes den högsta av de siffror, som kunna ifrågakomma.</p>

a) Allmän utbildning m.m. | Beteckning
-- | --
Enskild undervisning | 1, 4, 5
Småskolor | 3
Folkskolor | 3
Ersättningsskolor | 3
Fortsättningsskolor | 4
Nomadskolor | 3
Blindskolor och –institut | 3
Dövstumskolor och –institut | 3
Småskoleseminarier | 4
Folkskoleseminarier | 5, 7
Blind- och dövstumsskoleseminarier | 5
Högre folkskolor | 4
Borgarskolor | 4
Folkhögskolor | 4
Pedagogier | 5
Kommunala och enskilda mellanskolor | 5
Allmänna och enskilda real- och samskolor | 5
Högre allmänna och enskilda läroverk | 5
Statens normalskola för flickor | 5
Högre flickskolor | 5
Realskoleexamen | 5
Högre lärarinneseminarier | 8 eller 5
Universiteten | 9
Karolinska institutet | 9
Stockholms högskola | 9
Göteborgs högskola | 9

Socialpolitiska institutet | 5 eller 7
Landsfiskalsexamen | 5
Kronolänsmansexamen | 5
Postverkets undervisningsanstalter | 4, 5, 7
Telegrafverkets undervisningsanstalter | 4, 5, 7
Tullverkets undervisningsanstalter | 4, 7
Statens järnvägars undervisningsanstalter | 4, 5, 7

Korpralsskola | 4
Underofficersskola | 5
Krigsskolan | 8
Sjökrigsskolan | 8
Ridskolan å Strömsholm | 8
Infanteriskjutskolan å Rosersberg | 8
Krigshögskolan | 8
Artilleri- och ingenjörshögskolan | 8
Sjökrigshögskolan | 8
Majorskurs | 8

Hushållsskola, ej särskilt nämnd | 4
Husmodersskola | 4
Fackskolan för huslig ekonomi i Uppsala | 5
Statens skolköksseminarium och hushållsskola | 5
Skolköksseminarier | 5

Barnavårdsskolor och –kurser | 4
Undervisningsanstalter för barnmorskor | 4
Anstalter för sjuksköterskeutbildning | 4, 5
Gymnastiska centralinstitutet | 5, 8
Arvedsons gymnastikinstitutet | 5
Sydsvenska gymnastikinstitutet | 5
Tandläkareinstitutet | 8
Farmaceutiska institutet | 8

Veterinärhögskolan | 8
Röda stjärnan | 4

Lantmannaskola | 4
Lantbruksskola | 4
Lantbruksinstitut | 5, 8
Kontrollassistentkurser | 4
Trädgårdsskolor | 4
Mejeriskolor | 4

Lärlingsskolor | 4
Yrkesskolor | 4
Tekniska skolor, ej särskilt nämnda | 4
Tekniska aftonskolor | 4
Verkstadsskolor | 4
Hantverksskolor | 4
Verkmästarskolor | 4
Chaufförsskolor | 4
Tekniska elementarskolor | 5
Tekniska fackskolor | 5
Tekniska gymnasier | 5
Tekniska skolan i Stockholm | 5
Tekniska högskolan | 8
Chalmers tekniska institut | 5, 8
Bergsskolor | 5, 8, 9
Slöjdskolor | 4
Hemslöjdskolor | 4
Sömnadsskolor | 4
August Abrahamsons stiftelse | 4
Vävskolor | 5
Handarbetslärarinneseminarier | 5
Bokhantverksskolor | 4
Byggmästarskolor | 4
Frisörskolor | 4
Konditorifackskolor | 4
Järnhandlarefackkurser | 4
Skrädderiskolor | 4
Tillskärareskolor | 4
Tegelmästareskolor | 4

Praktiska skolor | 4
Handelsskola, ej särskilt nämnd | 4
Bokhandelsskola | 5
Handelsinstitut | 5
Handelsgymnasier | 5
Handelshögskolor | 5, 8
Navigationsskolor | 5
Sjömanselevskolor | 4

Enskilda musikskolor | 4
Enskilda konstskolor | 4
Musikkonservatoriet | 5
Konsthögskolan | 5
Högre konstindustriella skolan i Stockholm | 5

Kolportörskolor | 4
Evangelistskolor | 4
Predikantskolor | 4
Bibelinstitut | 4
Missionsskolan å Johanneslund | 5
Missionsskolan å Lidingö | 5
Metodistseminariet i Göteborg | 5
Betelseminariet | 5
