### ISSUE TITLE
Maskinläsbardata önskas så vi kan för ett visst datum veta om dödboken i församlingen finns släppt

### ISSUE THREAD

**Issue by salgo60** [Riksarkivet/dataplattform#15]
**User case 1:** Jag som släktforskare vill komplettera med referens till dödboken

* när en dödbok finns släppt så skall denna uppgift komma upp på min att göra lista

Gränssnitt önskas:
* SPARQL med federation Wikidata att föredra
* annars Notebook och json API

**User case 2:** Vi letar dödsorsaker för svenska Riksdagsmän [#126](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/128), dödsorsaken finns ofta i kyrkboken --> praktiskt att kunna lista dom kyrkböcker som finns släppta och digitaliserade idag där vi saknar dödsorsak för svenska Riksdagsmän
* idag kan vi [skapa en rel. bra lista](https://w.wiki/6hoP) men måste klicka oss igenom posterna för att **se status hos Riksarkivet**...

**Comment by nilsw-ra** [comment]
"När en dödbok finns släppt", vad avses med släppt i detta fallet? Jag ser tre tänkbara varianter:

1. När den finns digitiserad, dvs bilden tillgänglig i söktjänsten
2. När den finns digitiserad **och** rättighetsmärkt, dvs bilden tillgänglig i söktjänsten och via externt IIIF-anrop
3. När den finns indexerad och sökbar, som https://sok.riksarkivet.se/dodregister

Vi kommer inte att ha någon dedicerad sökingång i sök-APIet för att söka arkivenheter som är just dödböcker, men man kan söka på fritext "dödbok", anropet kommer att se ut som

`https://data.riksarkivet.se/api/records?text=dödbok`

Vi har idag inga metadata som identifierar en volym som en dödbok.

Sök-APIet kommer att leverera sökresultatet i JSON, med länkar till enstaka posterna i RDF (RDF/XML och JSON-LD). Det finns för närvarande inga planer på en SPARQL endpoint.

**Comment by salgo60** [comment]
> "När en dödbok finns släppt"

När Karin Söders dödbok i [listan nedan](https://w.wiki/6hyE) finns digitaliserad och tillgänglig för mig att använda via ert UI eller via Arkivs Digitals produkt....

* listan nedan är 2300 riksdagspersoner och kollar vi på svenska Wikidata svenskar som avlidit är det [28 000 personer lista](https://w.wiki/6hyY) detta skalar inte att sitta och klicka i en lista för att kolla vilka av kyrkböckerna som finns släppta..

[<img width="1435" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/0ad9af2f-37b6-4dc2-b619-67064ae3adef">](https://w.wiki/6hyE)


## Stänger denna
* **stänger denna** känns inte som vi har samma målbild 😭 tror nästan det är enklare att vi lägger denna info i Wikidata ....
   * känns inte bra att mer och mer kopplingar ligger i Wikidata som borde födas från Riksarkivet plus att **[att vi försöker bjuda in er sedan 2016 under 7 år](https://github.com/salgo60/Svenskaforsamlingar/issues/3)**  jag är idag på [Open science](https://oppenvetenskap.se/) och pratade med bland annat [Michael Arentoft is Head of Unit, Open Science, DG R&I, European Commission](https://oppenvetenskap.se/michael-arentoft/) och dom vill se kunskapsgrafer modell [openaire](https://graph.openaire.eu/) och citizen science - **vad vill Riksarkivet??** - se fråga [chatGPT vad ni behöver för nya kompetenser som organisation](https://github.com/salgo60/DiggUptime/issues/70#issuecomment-1438535775)
      * koppling [kyrkbok SBL görs enklast i Wikidata](http://minancestry.blogspot.com/2017/05/sbl-wikidata.html)
         * koppling [VIAF LIBRIS finns i Wikidata](https://w.wiki/6iLP)
         * [660 olika externa källor"auktoriteter" kopplar Wikidata idag personer i SBL till](https://w.wiki/6iLR)
         
         [<img width="884" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/81eaaa8c-c6b7-44c8-992d-096c89ea27b8">](https://w.wiki/6iLS)

      * koppling [karta - kyrkbok görs i Wikidata](https://salgo60.github.io/Svenskaforsamlingar)
      * koppling [NAD person arkiv - SBL börjar göras i WD](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/104)
      * koppla [Riksdagsmän - namnet som objekt - SBL görs i Wikidata](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/142)
      * koppling [distrikt <-> församling](https://sv.wikipedia.org/wiki/Kategori:Distrikt_i_Sverige)görs i Wikipedia/WD
      * koppling [distrikt <-> församling <-> Svenska Hembygdsförening/Bygdeband görs i Wikidata](https://github.com/salgo60/WikidataBygdeband/issues/4)
      * [artikel om församlingen NAD görs i Wikipedia](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/104)
      * koppling [kyrka - församlingen sker i Wikidata/Wikipedia](https://sv.wikipedia.org/wiki/Kategori:Svenska_kyrkans_f%C3%B6rsamlingar)
      * koppling [gravstensinventeringen - Wikidata - begravningsplatser](https://github.com/salgo60/Gravstensinventeringen) - SBL - kyrkbok sker i WD
      * koppling [kyrkbok - kyrka - personer i bok om kyrkan från RAÄ- Riksarkivet SBL](https://w.wiki/3Dd) finns i Wikidata 
         * exempel bok [RAÄ om Riddarholmskyrkan -> person -> SBL](https://w.wiki/3Dd) finns i Wikidata
         * exempel hur [kyrkor kopplas till karta - RAÄ böcker om kyrkan - församling kyrkböcker](https://github.com/salgo60/SamlaLibris)
      * koppling kyrkbok - kyrka - Open Street Map/ Google Map finns i Wikidata
      * koppling kyrkbok - person - [dödsorsak finns i WD](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/128)
      * koppling [Sveriges befolkning 1930 - inkomst - Riksdagsman - Wikidata](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/103)
      * [namn som används](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/142) håller Wikidata reda på som objekt...

* [exempel koppling exempel koppling bok om Riddarholmskyrkan och personer i boken som finns i Riksarkivet SBL eller har arkiv hos Riksarkivet, finns i kyrkböckerna ](https://w.wiki/3Dd) - **Wikidata har kopplingarna**
<img width="973" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/90d02230-68c8-494c-86b2-5630a5d736bf">

Vore bra om det kom en roadmap om kommande leveranser och vad vi inte skall satsa på att ha i Wikidata. Var är er vision...

**Comment by salgo60** [comment]
Exempel skillnad hur Arkiv Digital har klickbara länkar och Riksarkivet **[Strings not Things](https://github.com/salgo60/DiggUptime/issues/77#issuecomment-1308635367)** - [SE/GLA/13212](https://sok.riksarkivet.se/?postid=ArkisRef%20SE/GLA/13212) = WD [Hogdals församling](https://w.wiki/6ig3) borde vara [5-stardata](https://5stardata.info/en/) [#30](https://github.com/salgo60/Svenskaforsamlingar/issues/30)

<img width="1222" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/fa63e7de-631e-474f-b282-0a97041ce7a1">

<img width="1143" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/f74a260a-8cc3-4bcc-a56b-3605c8baadf2">
