### ISSUE TITLE
Beskriver Riksarkivet sitt data

### ISSUE THREAD

**Issue by salgo60** [Riksarkivet/dataplattform#16]
* Internet Archive

----

På [Open science](https://oppenvetenskap.se/) i Stockholm pratar man om att data måste beskrivas bland annat [Michael Arentoft Head of Unit, Open Science, DG R&I, European Commission](https://oppenvetenskap.se/michael-arentoft/) och han pekade även på att kunskapsgrafer tas fram se [openaire](https://graph.openaire.eu/) 

* i WIkidata testar vi nu [ShEx se #129](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/129) - se fråga [#144 Umeå Familia](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/144)
   * datat sig själv är ofta Things not strings där Things i sin tur beskrivs i en eller flera Wikipedia artiklar... ibland lite spretigt men det arbetas hela tiden med kvaliten...

**Finns Riksarkivevts dokumentation samlade om ert data?** och hur beskrivs datat idag och vad är framtidsplaner som att ha [5 star data](https://5stardata.info/en/)

**Comment by nilsw-ra** [comment]
Publika data kommer att finnas beskrivna i dokumentationen i detta GitHub-repo. Enskilda poster kommer att ha RDF-representation.

**Comment by salgo60** [comment]
Kan ni inte ha en utvecklingsmodell att ni har en **backlog** med det som komma skall och ni stänger först då saker levererats --> att man kan prenumerera på status? variant att ni dokumenterar hur ni jobbar och har en roadmap med tydliga releaser där varje leverans anger vad som produktionssätt... nu känns det lite som Riksarkivet är lite utanför [projekt som Riksdagens corpus](https://github.com/welfare-state-analytics/riksdagen-corpus/issues/300#issuecomment-1556151367) men skall Riksarkivet bli en del i ett digitalt ekosystem så krävs tydlighet....

* se jobba [agilt med CRISP](https://www.youtube.com/watch?v=HTX4UScy6kI)
* OT extremt dåliga svarstider på Riksarkivet tjänster i helgen [#45](https://github.com/salgo60/Svenskaforsamlingar/issues/45) men gissar att det är annan del av riksarkivet borde dock finnas centrala tjänster jmf [Wikidata kör Grafana](https://grafana.wikimedia.org/d/000000489/wikidata-query-service?orgId=1&refresh=1m)

* [#15](https://github.com/salgo60/Svenskaforsamlingar/issues/15) "Riksarkivet: Tydlighet vad som skall levereras och när det görs"
