### ISSUE TITLE
Riksarkivet: Hantera Persistenta Identifierare i arkiverat material via API:er vad är status?

### ISSUE THREAD

**Issue by salgo60** [Riksarkivet/dataplattform#17]
* [internet archive web.archive.org/web/20240526111731](https://web.archive.org/web/20240526111731/https://github.com/Riksarkivet/dataplattform/issues/17)
----

Riksarkivet har haft ett regeringsuppdrag att arbetat med att förvalta och vidareutveckla  och främja myndigheternas arbete med data för vidareutnyttjande -  en del i detta är **persistenta identifierare**

Riksarkivet har bl.a. producerat nedanstående dokument men jag ser inte att någonstans beskrivs **Persistenta Identifierare i arkiverat material**
* 2017 utrett [Öppna data och PSI](https://riksarkivet.se/Media/pdf-filer/doi-t/oppna_data_och_psi_sanja_halling.pdf)
* 2016 "[Riksarkivets förstudie om att samla in och publicera förteckningar som ska publiceras enligt lagen om vidareutnyttjande av handlingar från den offentliga förvaltningen](https://riksarkivet.se/Media/pdf-filer/Bilaga%205%20-%20Riksarkivets%20f%C3%B6rstudie%20om%20PSI-f%C3%B6rteckningar.pdf)"
  * slides [Riksarkivets kartläggning av användarbehov kring öppna datamängder och s k PSI-förteckninga](url)

2023 startar DIGG med att [hanterar en rekommendation kring beständiga identifierare](https://github.com/diggsweden/persistent-identifiers-investigation) där att hantera dessa i arkiverat material måste beaktas i exempelvis "[Best practices](https://github.com/diggsweden/persistent-identifiers-investigation/issues/4)" till alla aktörer

**Fråga A:** Kan man via Riksarkivets API:er eller annat sätt hämta arkiverade dokument/resurser med deras PID:ar
**Fråga B:** Vem äger detta problem att Persistenta Identifierare skall vara persistenta även vid arkivering? Riksarkivet/Arkiverande myndighet/???
**Fråga C:** Skall detta fungera behövs [GUPRI](https://github.com/salgo60/DiggUptime/issues/54) med API. Vem äger denna fråga hos Riksarkivet och var finns det beskrivet hur detta fungerar med arkiverat material?
**Fråga D:** Har ni kommunicerat era krav till DIGG? Var förs dialogen?

Exempel hur saker idag är ett mindre kaos
* Domstolsverket jobbar 26 år med att skapa interoperabilitet mellan 100 myndigheter och status 2023 är att dom inte ens kan peka på författningar från myndigheter som upphört dvs. dagens aktörer klarar inte av sin uppgift trots att dom har haft 26 år på sig att leverera och bygga upp kompetens - [Domstolsverket analys av läget](https://github.com/salgo60/LagrummetLight/issues/1)
* #87 [Dokument "försvinner" vid regeringsskiften...](https://github.com/salgo60/DiggUptime/issues/87)
* Vi behöver [best practices](https://github.com/diggsweden/persistent-identifiers-investigation/issues/4) som stödjer hela dokumenthanteringsprocesen även vid arkivering och då en myndighet upphört.... det lilla jag ser så verkar det inte tagits höjd för att vara Digitala utan det är mer hantering av flyttkartonger som flyttas till en arkivhylla....
   * API:er SPARQL etc. måste stödja detta
   * EN [GUPRI-hub](https://github.com/diggsweden/persistent-identifiers-investigation/issues/2) för statens alla dokument/resurser/dataset/aktörer... skulle spara enormt med tid och pengar

-----
## Varför Persistenta Identifierare är viktiga
Se [FAIRDATA F1](https://www.go-fair.org/fair-principles/f1-meta-data-assigned-globally-unique-persistent-identifiers/)

<img width="1135" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/6ae1121e-0d12-43a6-9496-f23264cbcc25">

**Comment by salgo60** [comment]
PID:af har funderats över i denna rapport 2018-06 men ser inte att Riksarkivet pekar på hur arkivering är en del och ingen leverans verkar ha skett?!?!?
 
* [Slutrapportering av uppdrag om att främja statliga myndigheters arbete med att tillgängliggöra data för vidareutnyttjande](https://riksarkivet.se/media/pdf-filer/slutrapport-regeringsuppdrag-riksarkivet-180627.pdf)

<img width="699" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/b279034f-1230-449e-b200-ee69004b0905">
<img width="699" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/4f85cf1f-5503-4a73-a3a3-f11147a65d6f">
<img width="699" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/d564869c-372d-4a0e-8464-17ea46547705">

**Comment by nilsw-ra** [comment]
I princip måste jag svara samma sak på alla fyra frågorna A-C. Inget av detta är aktuellt/möjligt med dagens förutsättningar i och med att Riksarkivet i de allra flesta fallen inte hanterar data för enstaka dokument. Vi har nästan enbart data på samlingsnivå: arkiv, serie och volym. Vidare så ger vårt kommande sök-API inte bara tillgång till Riksarkivets egna arkivmaterial, inte det som andra aktörer levererar til NAD.

**Comment by salgo60** [comment]
@nilsw-ra perfekt då är frågan för några att besluta om det är önskvärt min tro är att "[Det är i högsta grad en demokratifråga att dokument överlever organisationer](https://github.com/diggsweden/persistent-identifiers-investigation/issues/2#issuecomment-1579957685)" --> att Riksarkivet borde vara den naturliga aktören att ha den tjänsten...

Har en dialog med projektet Riksdagens-Corpus där jag gissar att det är ett "krav" från forskare att Persistemta Idemtifierare och PID grafer kan tas fram enkelt....
* känns fel att Riksdagens-Corpus jobbar med att skapa bra data och att staten 2023 inte skapa TEI, använder persisteta identifierar eller har API:er

Tankar finns nu att detta projekt börjar jobba med  [LLM](https://en.wikipedia.org/wiki/Large_language_model) för att berika sin KG

**Comment by nilsw-ra** [comment]
Tanken är förvisso god och det är logiskt att hantera arkiverat material på Riksarkivet. Som du noterar finns dock inet konkret uppdrag och ingen samordning mellan myndigheter i frågan.

**Comment by salgo60** [comment]
:smiley: jag som sitter på läktare tycker det finns många udda saker i denna ekvation...
* varför Riksarkivet själva inte pekade på detta då man hade "bollen" och utredde detta... 
* att DIGG inte involverar Riksarkivet... eller kanske ni finns med
* att forskarna som [Riksdagens Corpus](https://www.umu.se/nyheter/5-miljoner-till-forskning-om-lankad-parlamentariska-data_11678700) lägger ned > 5 miljoner på något som borde finnas i det data Riksarkivet / Riksarkivet SBL arkiverar / producerar....
   * var kommunicerar dom sina krav eller har dom gett upp
   * syns tydligt i @matthiaspalmer svar att han inte ser forskare som HUMLABs behov som ett User Case utan försöker förenkla dokumentlivscykeln och vilka user case dom skall stödja...
     * tror roller och kompetens i projekt som detta måste tydliggöras jag har efterfrågat [Best practices i projektet Uppdrag att utveckla en sammanhållen datainfrastruktur för kompetensförsörjning och livslångt lärande](https://gitlab.com/arbetsformedlingen/uppdrag-att-utveckla-en-sammanhallen-datainfrastruktur-foer-kompetensfoersoerjning-och-livslangt-laerande/-/issues/17) där kompetens och roll borde vara en del att beskriva på dom som deltar i en utredning...
     
 **@matthiaspalmer tanke** - känns inte persistent...
 > att skapa tekniska lösningar för persistens när det inte finns organisationer bakom som stödjer blir inte bra

**Comment by salgo60** [comment]
@nilsw-ra  FYI jag sköt ut mig ur [DIGG diskussionen om "persistenta" identifierare](https://github.com/diggsweden/persistent-identifiers-investigation/issues/1#issuecomment-1583569563) så vill Riksarkivet vara med i diskussionen så tror jag ni måste bjuda in er själva (UPDATE: verkar som er gubbe [ Fredrik Emanuelsson är med i en referensgrupp](https://github.com/diggsweden/persistent-identifiers-investigation/blob/main/process/index.md#referensgrupp) så snacka ihop er)... idag verkar "persistent" inte involvera hela [dokument cykeln](https://www.regionarkivet.regionstockholm.se/images/18.15c5259015c4300800c1191/1503487300778/Information_Livcykelperspetiv.png) jmf [hur identifierare från 1750 lever ännu idag](https://meta.wikimedia.org/wiki/Structured_data_for_GLAM-Wiki/Roundtripping/KMB) mitt [föredrag 2021 på LD4 om detta](https://www.youtube.com/watch?v=GeDXzInR_mA) vid [7 min pratar jag om runstenar 1750](https://www.youtube.com/live/GeDXzInR_mA?feature=share&t=423)

![image](https://github.com/Riksarkivet/dataplattform/assets/14206509/971678ef-99bb-478c-97b5-f30ff903dc92)

![image](https://github.com/Riksarkivet/dataplattform/assets/14206509/ba3b3050-fced-4e7c-a4e1-ea4d953a9eb0)

----
Känns galet att inte ha en **gemensam modell över informationens livscykel** där persistenta identifierare för informationsobjekt på ett naturligt sätt passar in.... 
* jag skapade teknisk lösning för några myndigheter som Skolverkets och Luftfartsverkets författningssamlingar på 90-talet och där finns en enorm mognad att nya författningar skapas som ersätter andra och nya kommer till som är ändringsförfattningar som sedan upphör författningar - samma flöde måste finnas för myndigheter, dokument.... det känns som saker blir enormt taffliga om alla skall hitta på sin egen världsbild... ja ja det är inte konstigt att saker inte fungerar...

**Comment by salgo60** [comment]
En ”Riksarkivet DOI” lösning som lever under hela dokumentens/datasetens livslängd borde vara perfekt för alla och särskilt vid arkivering… se [tweet](https://twitter.com/landgren/status/1671284616580268033?s=46&t=D6oLWi5wBnn3mz_lLtUSGw)

![IMG_8552](https://github.com/Riksarkivet/dataplattform/assets/14206509/dfb666d1-e29b-41ae-9f1c-cd0c80e1bbda)

![IMG_8553](https://github.com/Riksarkivet/dataplattform/assets/14206509/ace55cda-aa0b-44c0-a5b3-92f1e4bbf1d3)

* mer om [DOI på Wikipedia](https://en.wikipedia.org/wiki/Digital_object_identifier)

**Comment by salgo60** [comment]
Uppdatering:
* önskan att [DIGG tar tag i detta #23](https://github.com/diggsweden/persistent-identifiers-investigation/issues/23)

Lyssnar man på [Riksarkivets presentation 30 november 2023](https://youtu.be/AVH3gPwB63M?si=OXzZeh2USDxXcRG-&t=1050) så saknar vi även att dom har en förståelse och en plan för persistenta identifierare 2023 dec....

<img width="957" alt="image" src="https://github.com/diggsweden/persistent-identifiers-investigation/assets/14206509/f33a68fa-01c9-48f4-af6e-4b5c989d43ec">

**Comment by salgo60** [comment]
frågan ställdes direkt till Riksarkivets chefsjurist [Jens Västberg](https://se.linkedin.com/in/jens-v%C3%A4stberg-61466182) 2024-jan om detta diskuteras med persistenta identifierare men inget han hört
