### ISSUE TITLE
Beskriv gärna begrepp som "arkivenhet" för oss dödliga

### ISSUE THREAD

**Issue by salgo60** [Riksarkivet/dataplattform#18]
såg på [Exempel](https://github.com/Riksarkivet/dataplattform/wiki/Exempel)
_persistent id för arkivenheten (arkiv, serie, volym etc)_

Tycker rättsinformationssystemet hade trevligt sätt att [dokumentera](http://dev.lagrummet.se/dokumentation/) [begrepp](http://dev.lagrummet.se/dokumentation/model.pdf) etc... plus som DIGGs projekt [Beständiga identifierare poängterar](https://github.com/diggsweden/persistent-identifiers-investigation/issues/6) uttrycker sig "_så vi kan formulera oss enhetligt och kommunicera tydligt_" idag gissar vi när vi skapar egenskaper som [P5324](https://www.wikidata.org/wiki/Wikidata:Property_proposal/National_Archive_of_Sweden) / [P9713](https://www.wikidata.org/wiki/Wikidata:Property_proposal/NAD_agent_ID) här vore det snyggaste om vi kunde länka tillbaka till er definition som skulle finnas på engelska och svenska...

* finns en poäng med att Riksarkivet beskriver vad termer som **arkivenhet** betyder i eran värld...
   * jag vill ju se allt hos Riksarkivet [digitalt med PID-grafer](https://github.com/salgo60/DiggUptime/issues/70#issuecomment-1586114522) men gissar att "arkivenhet" inte innebär det by default :rocket:
* även gärna peka på om det finns en [introduktion modell den lagrummet skrev](http://dev.lagrummet.se/dokumentation/introduktion/intro-implementatorer.html)

Bäst vore om DIGG hade en central termkatalog/ att "samma termer" "återanvändes"... att saker som begrepp fanns som länkad data... och grafer typ nedan kunde skapas.... **gissar att röra sig från digitala silos till en länkad miljö kräver samma begrepp och mycket kommunikation...**
* även att grafer kunde skapas mellan myndigheters information och kunna se vilka andra system använder ord som _arkivenhet_ = med samma betydelse som det Riksarkivet menar
   * se hur Wikidata idag har Scholia som skapar visualiseringar som ovan... 
        * [Öresundsbron Q297871](https://scholia.toolforge.org/topic/Q297871) - egen [graf](https://w.wiki/6pud) [en](https://w.wiki/6pvU) [ar](https://w.wiki/6pvV) - [författare som motionerat om Öresundsbron i Riksdagen](https://w.wiki/6pnh)
        * [Ostkustbanan Q1049808](https://scholia.toolforge.org/topic/Q1049808)
        * [Författare kopplat till ämnen de motionerat om rörande järnvägsinfrastruktur från 2009 och framåt](https://w.wiki/569u)

<img width="1289" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/ca63ad8a-9a51-41e7-87af-1c013ac3f394">

**Comment by salgo60** [comment]
Hittade [RIKSARKIVET Dnr 60-1146-92 NATIONELL ARKIVDATABAS - DATAELEMENTKATALOG 1993-10-15 2.4 ](http://xml.ra.se/EAC/dataelementkatalog1993.pdf)

* Känns inte som det uppdaterats sedan 2005
  * saknar helt detta med persistenta identifierare och tankar om kunskapsgrafer, 5stardata
     * se kommentar till [LIBRISXL](https://github.com/salgo60/spa2Commons/issues/28#issuecomment-1480983678) -  [Human: Förklara enkelt vad fördelen är med en kunskapsgraf jämfört med hur biblioteken normalt jobbar med Dewey](https://datafit.ai/prompt/15297)
  * verkar vara old school och bygga på Marc och någon egen variant NADMARC som jag inte ser tar höjd för persistenta identifierare....
      * Leverans till [NAD_lathund](https://riksarkivet.se/Media/pdf-filer/NAD/Leverans%20till%20NAD_lathund.pdf)
  * finns en ordlista men inte ordet "arkivenhet"
----
* WD kopplingar P5324 - 7715 stycken
  * [P5324](https://www.wikidata.org/wiki/Property_talk:P5324)
     * [karta](https://w.wiki/6pzz)
     * [lista](https://w.wiki/6p$5)
     * [bilder](https://w.wiki/6p$6)
     * [andra externa egenskaper i WD](https://w.wiki/6q2t) = 581 stycken/ [alla egenskaper på dessa kopplade objekt](https://w.wiki/6q2v) = 846
     
<img width="1302" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/969c45a7-e89f-41b3-b7fa-5a3cb07144d1">

<img width="1342" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/2a17bb85-a900-4637-8c36-b74d1b79a086">

<img width="1348" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/701eddfc-3357-4531-9d6e-cc6e008f116d">

<img width="1348" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/fa6d3473-bba7-4b6a-8884-26fa6e5f5a9a">

<img width="1348" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/adcfcfe8-74ea-4a26-8e95-cd814c4902af">

----
* WD kopplingar 1186 stycken
  * [P9713](https://www.wikidata.org/wiki/Property_talk:P9713)
     * [karta](https://w.wiki/6p$L)
     * [lista](https://w.wiki/6p$q)
     * [bilder](https://w.wiki/6p$S)
     * [andra externa egenskaper i WD](https://w.wiki/6q37) = 351 / [alla egenskaper](https://w.wiki/6q32) = 538
          
<img width="1342" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/abdd3f72-d3b3-4487-b0a3-76e080be44eb">

<img width="1348" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/23e3aef2-70fa-4404-a082-7b87e0fe8d64">

* NAD agent kopplad med P9713 till en [Svenska Riksdagsmän på en tidslinje](https://js.histropedia.com/apps/query-timeline/index.html?q=SELECT%20distinct%20?person%20?personLabel%20(SAMPLE(?SPA)%20AS%20?SPA)%20%20(sample(?bild)%20AS%20?bild)%20%0A?birth%20?death%20?partyLabel%20?NADagent%20WHERE%20%7B%0A%0A%20%20VALUES%20?member%20%7B%0A%20%20%20%20wd:Q33071890%20%0A%20%20%20%20wd:Q81531912%20%0A%20%20%20%20wd:Q82697153%20%0A%20%20%20%20wd:Q10655178%20%0A%20%20%7D%0A%20%20?person%20wdt:P39%20?member.%0A%20%20OPTIONAL%7B?person%20wdt:P102%20?party%7D%0A%20%20OPTIONAL%7B?person%20wdt:P569%20?birth%7D%0A%20%20OPTIONAL%7B?person%20wdt:P570%20?death%7D%0A%20%20OPTIONAL%20%7B?person%20wdt:P18%20?bild%7D.%0A%20%20%7B?person%20wdt:P9713%20?NADv%7D%0A%20%20BIND(URI(CONCAT(%22https://sok.riksarkivet.se/agent/%22,?NADv))%20AS%20?NADagent)%0A%20%20SERVICE%20wikibase:label%20%7B%20bd:serviceParam%20wikibase:language%20%22sv,en%22.%20%7D%0A%7D%20GROUP%20BY%20%20?person%20?personLabel%20%20?death%20?birth%20?partyLabel%20?NADagent%0Aorder%20by%20?partyLabel&d=0&md=true&g=article&l=NADagent&t=personLabel&s=birth&e=death&i=bild&c=partyLabel&f=partyLabel&v=t)
   * [icke kopplade Riksdagsmän](https://js.histropedia.com/apps/query-timeline/index.html?q=SELECT%20distinct%20?person%20?personLabel%20(SAMPLE(?SPA)%20AS%20?SPA)%20%20(sample(?bild)%20AS%20?bild)%20%0A?birth%20?death%20?partyLabel%20WHERE%20%7B%0A%0A%20%20VALUES%20?member%20%7B%0A%20%20%20%20wd:Q33071890%20%0A%20%20%20%20wd:Q81531912%20%0A%20%20%20%20wd:Q82697153%20%0A%20%20%20%20wd:Q10655178%20%0A%20%20%7D%0A%20%20?person%20wdt:P39%20?member.%0A%20%20OPTIONAL%7B?person%20wdt:P102%20?party%7D%0A%20%20OPTIONAL%7B?person%20wdt:P569%20?birth%7D%0A%20%20OPTIONAL%7B?person%20wdt:P570%20?death%7D%0A%20%20OPTIONAL%20%7B?person%20wdt:P18%20?bild%7D.%0A%20%20minus%20%7B?person%20wdt:P9713%20?NAD%7D%0A%20%20SERVICE%20wikibase:label%20%7B%20bd:serviceParam%20wikibase:language%20%22sv,en%22.%20%7D%0A%7D%20GROUP%20BY%20%20?person%20?personLabel%20%20?death%20?birth%20?partyLabel%0Aorder%20by%20?partyLabel&d=0&md=true&g=article&l=person&t=personLabel&s=birth&e=death&i=bild&c=partyLabel&f=partyLabel&v=t) > 2000
   
<img width="1213" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/af0bbb47-451b-4ad5-9ad2-48f45d3ee1e8">
----

### Nad agent - Riksarkivet SBL - WD
* [Riksdagsmän](https://w.wiki/6p$i) = 35 stycken
   * [alla = 50](https://w.wiki/6p$k)

**Comment by nilsw-ra** [comment]
Bra poäng, jag ser till att göra en begreppsförklaringssida i Wikin.

**Comment by salgo60** [comment]
@nilsw-ra tack för lite förklaringar [RDF-arkivenheter](https://github.com/Riksarkivet/dataplattform/wiki/RDF-arkivenheter)

intressant [rico:hasOrHadIdentifier](https://www.ica.org/standards/RiC/RiC-O_v0-2.html#hasOrHadIdentifier) / [Class: rico:Thing](https://www.ica.org/standards/RiC/RiC-O_v0-2.html#Thing)

<img width="1016" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/9d4c0159-8403-43f9-9e6d-f7911b9a2c11">

Kanske **dum fråga** kan man se om det används i Riksarkivets data?
-----
OT
* Records in Contexts (RiC)  [presenteras i denna video 49:30 min](https://www.youtube.com/watch?v=oHG_pupre8w&t=2970s) - GITHUB [ICA-EGAD/RiC-O](https://github.com/ICA-EGAD/RiC-O) / Google group [Records_in_Contexts_users](https://groups.google.com/g/Records_in_Contexts_users)

**Comment by nilsw-ra** [comment]
rico:hasOrHadIdentifier används i RDF-representationen för referenskod och (eventuellt) extraid. Se t.ex. https://data.riksarkivet.se/archive/4mZWR0rz2Y3SmsduZ8aHI4.jsonld

**Comment by salgo60** [comment]
Tackar vore bra om ni hade json-ld länk på alla era sidor jmf [LIBRISXL](https://libris.kb.se/k3w87tsw36mkq44)

----
OT Just detta att era IDn inte syns i URL:en gör det extra krångligt att hoppa till er se [video](https://youtu.be/Ugf2tfS2N6E) med Chrome extension [Entity Explosion](https://www.wikidata.org/wiki/Wikidata:Entity_Explosion)

**Comment by nilsw-ra** [comment]
RDF-representationen är i beta-version än så länge. Så småningom kan vi nog ta med länkar till JSON-LD och RDF/XML på söktjänstens presentationssidor. ID finns i RDF-URIerna och söktjänstens permalänkar (men däremot tyvärr inte i URL-erna i söktjänstens resultatlista, där är det den UUID som ligger till grund för PID).
