### ISSUE TITLE
Wikidata <-> Riksarkivet <-> Wikidata Riksdagens corpus

### ISSUE THREAD

**Issue by salgo60** [Riksarkivet/dataplattform#19]
Nu när API är på G borde vi kunna koppla ihop oss mer effektivt.... gissar att saker som ni tittar på med LLM etc... skapar möjliheter jag har svårt att inse... vilka skall ni koppla ihop er med? är Riksdagen Corpus en kandidat....

**Förslag:** Kanske vi skall träffas efter sommaren och snacka hur denna matchning skall ske på bästa sett.... det är en stort jobb men kan nog göras mer eller mindre effektivt plus att det är bra att veta vilka ambitions nivåer som finns - min lekstuga med [Riksdagsmön och NAD #104](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/104) / [svenska församlingar 2018](https://github.com/salgo60/Svenskaforsamlingar)

**Alternativt:** att ni samlar fler aktörer - vi får se om [DIGG får fart och kan leverera något bra med persistenta identifierare](https://github.com/diggsweden/persistent-identifiers-investigation/issues/6)... så borde dom gubbarna vara naturliga partners... känns som persistenta identifierare utan Riksarkivet by definition är fel tänkt...

**Tankar:**
1) Kandidat [Riksdagens Corpus](https://github.com/welfare-state-analytics/riksdagen-corpus/issues/324) som idag "bygger sitt data" på Wikidata men förhoppningsvis kommer att fixa bättre data 
    * deras planer med [egen persistent identifierar #269](https://github.com/welfare-state-analytics/riksdagen-corpus/issues/269)
    * lesson learned 2023 är att detta projekt idag jobbar perfekt med GITHUB [Issues](https://github.com/welfare-state-analytics/riksdagen-corpus/issues?q=is%3Aissue+), [PR](https://github.com/welfare-state-analytics/riksdagen-corpus/activity?activity_type=pr_merge) men lite geggigt med csv filer där posterna inte har identifierare --> halvt omöjligt att referera eller spåra...
1) [Riksarkivet SBL](https://github.com/salgo60/Svenskaforsamlingar/issues/6) måste ni tvingas in i detta det är galet att Riksdagens corpus inte hämtar sitt data från SBL utan leker med en hobby site som Wikidata - jag ställde frågan till SBL tidigare och helt galet svar - [vi har inte resurser](https://youtu.be/ywFsLrn43N0?t=2771) - att skapa en datafil med koppling SBL nummer - Arkiv id tar 0 sekunder gissar att dom springer runt en hel del i arkiven.... varför inte dokumentera det som Öppen data och inte interna post-it lappar.... nu körs projektet [Riksdagens Corpus](https://github.com/welfare-state-analytics/riksdagen-corpus) med > [5 miljoner i budget](https://www.umu.se/nyheter/5-miljoner-till-forskning-om-lankad-parlamentariska-data_11678700)... som i en perfekt värld inte hade behövts om [SBL](https://github.com/salgo60/Svenskaforsamlingar/issues/6), [KB](https://github.com/salgo60/spa2Commons/issues/15), [Riksdagens Öppna data](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/50) hade **[levererat data som data - RAW Datat now](https://youtu.be/OM6XIICm_qo?t=646)**
1) Ni borde skapa en task i en publik backlog "**Hur skall Riksarkivet skapa externa kopplingar....processen.... och vem som skall vara med**
   1) Lesson learned är att kvaliten ökar på datat med mera kopplingar mellan varandra.... idag tycket jag vi fastnat i en galen tunna som heter Wikidata där [12000 foliehattar](https://stats.wikimedia.org/#/wikidata.org) alla har sin egen agenda och inte producerar data som duger till forskningsdata eller verksamhetsdata... MEN känns ofta som det är den bästa datan...

**Comment by nilsw-ra** [comment]
Inget av detta finns mig veterligen med i Riksarkivets planering och utvecklingsresurserna är knappa, så det är knappast sannolikt att det tas in i planeringen i nuläget.

Frågeställningarna är intressanta men inte direkt relaterade till användning av APIerna, så jag noterar och stänger ärendet.

**Comment by salgo60** [comment]
© Ok det finns en [konferans 30 November](https://twitter.com/astrom_iko/status/1671543565535657984?s=20) med arkiv folk från er det är ju helst dom som skall driva detta.... och som borde ha en vision om saker som detta/ [persistenta identifierare](https://github.com/diggsweden/persistent-identifiers-investigation/issues/6) och [statens dokumenthantering #220](https://github.com/salgo60/DiggUptime/issues/220)

<img width="1018" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/e9ebe7e3-4a98-4183-b87b-2d7c99696d8f">

<img width="1018" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/0f981b5a-dec3-44c0-aff0-b7595819b13f">

**Comment by salgo60** [comment]
Annat mycket intressant projekt är KBs historiska tidningar där ni borde ha "samma som" och ni bör ha API:er som lirar ihop se dialog med dom https://feedback.blogg.kb.se/forums/topic/lankmodell/#post-24153 där det verkar vara så illa att dom inte skrivit sin app med [APIfirst](https://api1st.org/)

På Wikipedia startade Lars Aronsson som skapat Runeberg en diskussion att KB:s svenska historiska tidningar skulle kunna vara ett facit hur bra täckning Wikipedia har på historiska händelser platser personer... samma skulle kunna göras med Riksarkivet....

När jag gjorde en snabbkoll på "geggan" med svenska historiska yrken så såg man tydligt vilken "bias" databaser som Alvin har och samma kan man se på Wikidata att "arbetaryrken" saknas oftast medans adelgubbarna har bra närvaro https://github.com/salgo60/HISCOKoder
