### ISSUE TITLE
Stora bilder klipps/dupliceras

### ISSUE THREAD

**Issue by Abbe98** [Riksarkivet/dataplattform#2]
Om en bild är stor nog verkar den delas i flera och få sitt manifest/metadata duplicerad:

Exempel:
https://sok.riksarkivet.se/bildvisning/R0002568_00014
https://sok.riksarkivet.se/bildvisning/R0002568_00015

Upptäcka dublätterna går okej men att klippa ihop bilderna är lite krångligt, speciellt med tanke på att de överlappar.

**Comment by nilsw-ra** [comment]
Uppenbarligen har man scannat den aktuella kartan i två delar. Jag gissar att det beror på det långsmala formatet. Bilderna har varsitt item i manifestet, så de har varsin post i databasen. Såvitt jag kan se finns det ingen metadatakoppling mellan de två bilderna, att de avbildar samma fysiska föremål.
