### ISSUE TITLE
Beskriv ert data bättre

### ISSUE THREAD

**Issue by salgo60** [Riksarkivet/dataplattform#22]
* [internet archive web.archive.org/web/20240616073412](https://web.archive.org/web/20240617053120/https://github.com/Riksarkivet/dataplattform/issues/22)
* ChatGPT [Hur skall ett Riksarkiv beskriva sitt levererade data idag saknas termkataloger, backlogs och en enhetliget eller "samma som"](https://chatgpt.com/share/4fe7c92a-6ca0-4af1-adba-9b2970f627bd)
----

se lite feedback [#53 Riksarkivet SBL](https://github.com/salgo60/Svenskaforsamlingar/issues/53)

* utveckla gärna varför csv filer läggs i zipfiler som skall hämtas vad är vinsten? min [issue #54 ](https://github.com/salgo60/Svenskaforsamlingar/issues/54) vore smart om ni och [DIGG tänker lika](https://github.com/diggsweden/DCAT-AP-SE/issues/111#issuecomment-2137647605) så vi slipper massa handpåläggning.... tycker Wikidata SPARQL hur snyggt det blir om ni börjar koppla ihop saker med [5 star data](https://github.com/salgo60/Svenskaforsamlingar/issues/30)

* #1 gäller även nya dataset att vi vill se exempel med notebooks för dataset som [Riksarkivet SBL #53](https://github.com/salgo60/Svenskaforsamlingar/issues/53) / [Födda #54](https://github.com/salgo60/Svenskaforsamlingar/issues/54)....

* finns massa frågor till det ni gör skulle inte skada med beskrivning hur ni själva uppfattar den kvalitet ni levererar se det jag kallar metadata debt [#13](https://github.com/salgo60/Svenskaforsamlingar/issues/13)

**Comment by salgo60** [comment]
Samma typ av fråga 5 June 2023 #17 

Kan ni inte ha en utvecklingsmodell att ni har en backlog med det som komma skall och ni stänger först då saker levererats --> att man kan prenumerera på status? variant att ni dokumenterar hur ni jobbar och har en roadmap med tydliga releaser där varje leverans anger vad som produktionssätt... nu känns det lite som Riksarkivet är lite utanför https://github.com/welfare-state-analytics/riksdagen-corpus/issues/300#issuecomment-1556151367 men skall Riksarkivet bli en del i ett digitalt ekosystem så krävs tydlighet....

**Comment by DavidHaskiya** [comment]
Ingen av dessa frågor rör de publika API:erna. Stänger därför ärendet.

**Comment by salgo60** [comment]
@DavidHaskiya ?!?!? 

1.  beskriver ni inte ert data enhetligt?
2. vart ställer jag frågor om csv filer och excel extrakt?
3. finns det beskrivet gärna som öppen data var vi hittar 
* era API:er
  * planer på nya API:er/ backlog
* era csv extrakt
  * planer på nya extrakt / backlog
* era termer som Riksarkivet jobbar med jmf [wikidata properties](https://www.wikidata.org/wiki/Wikidata:Database_reports/List_of_properties/all) / önskan [dataverkstaden #32](https://github.com/salgo60/Anslagstavla/issues/32) / [#4](https://github.com/salgo60/StorsthlmWIkidata/issues/4)

**Comment by DavidHaskiya** [comment]
Våra API:er finns listade och dokumenterade här, https://github.com/Riksarkivet/dataplattform/wiki Vi arbetar inte med publik backlog. 

Våra nedladdningsbara dataset återfinns här, https://riksarkivet.se/psidata Kontaktperson för öppna data är Jens Kling, du kan mejla honom frågor du har. Vi arbetar inte med publik backlog. 

Jag vet inte vem du kan kontakta mer specifikt angående termer men generellt är avdelningschef Eva-Marie Sahlin informationsägare för våra arkiv.

**Comment by salgo60** [comment]
Ok 

* Eva-Marie Sahlin telefon 010-476 87 01 / [Linked in](https://www.linkedin.com/in/eva-marie-sahlin-26124710b/?original_referer=https%3A%2F%2Fwww%2Ebing%2Ecom%2F&originalSubdomain=se) / email ? / GITHUB ?
* Jens Kling telefon 010-476 73 15 / [Linked in](https://www.linkedin.com/in/jens-kling-013841131/?originalSubdomain=se) / email jens.kling@riksarkivet.se  / GITHUB ?

> Jag vet inte vem du kan kontakta mer specifikt angående termer men generellt är avdelningschef Eva-Marie Sahlin informationsägare för våra arkiv.

2018 hade vi en dialog med Olof Karsvall och Tora som blev [WD egenskaper](https://phabricator.wikimedia.org/T199858) men det känns som Tora inte tagit fart...
* bra beskrivning av Toras termer och tankar [Historical Settlement Units as Linked Open Data](https://ceur-ws.org/Vol-2364/24_paper.pdf)

2023 jobbade @nilsw-ra hos er och han försökte även skapa WD egenskaper som tyvärr dog och om jag fattar rätt så försvann han bort från Riksarkivet och ingen tog över detta

* issues stängs utan förklaring / borde vara pending eller annan status inte closed....
<img width="613" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/ecee5d26-5934-4901-a4f7-782e455838ce">

----

* #13 
* [Wikidata:Property proposal/National Archives of Sweden persistent identifier](https://www.wikidata.org/wiki/Wikidata:Property_proposal/National_Archives_of_Sweden_persistent_identifier)

### Tora
* T199977 [Test Federated search Wikidata SPARQL with TORA sparql (LIBRIS)](https://phabricator.wikimedia.org/T199977)
* T200065 [Define Libris and Tora as endpoints in Wikidata](https://phabricator.wikimedia.org/T200065)
* T233275 [Connect LOD Tora church parishes and administrative parishes with Wikidata](https://phabricator.wikimedia.org/T233275)
* T199862 [How should we manage/synchronize the creation of new/changed TORA/NAD objects in WD](https://phabricator.wikimedia.org/T199862)
* T234706 [Create a regexp for TORA P4820](https://phabricator.wikimedia.org/T234706)
* T251089 [Import of TORA ID – identifiers for places](https://phabricator.wikimedia.org/T251089)
* T199794 [Design how the TORA object should be mapped in Wikidata](https://phabricator.wikimedia.org/T199794)
* T199994 [TORA property "Church parish polygon" in WD <-> NAD SE/018821001](https://phabricator.wikimedia.org/T199994)
* [T225885](https://phabricator.wikimedia.org/T225885) Link Wikidata from Riksarkivet
* May 22 2019 [T224088](https://phabricator.wikimedia.org/T224088) Omstart 3 Riksarkivet
* T224089 [SBL ORCID](https://phabricator.wikimedia.org/T224089)
* T225859 [Connect NAD to personal archives](https://phabricator.wikimedia.org/T225859)
### Riksdagsmän <-> Riksarkivet 
* [#103](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/103) Riksdagsmän: Inkomst förmögenhet - Folkräkningar (Sveriges befolkning) 1930 et al
* [#153](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/153) Tidningsarkivet <-> önskan att KB Tidningsarkivet / Riksarkivet har semantisk interoperabilitet 
.....

### Other people trying to work with Riksarkivet
* Mar 27 2020 Open [T248665](https://phabricator.wikimedia.org/T248665)  Riksarkivet mini-project around Tora identifiers 
   * [T248666](https://phabricator.wikimedia.org/T248666) Confirm interest to RA and define next steps
   
## WD properties <-> Riksarkivet

* Riksarkivet https://w.wiki/AMXQ

<img width="1188" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/47f27fce-c058-4a9f-b996-cae68719b7cc">


* [svenska](https://w.wiki/AMXg)

<img width="1167" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/16279ac0-23e4-4b23-91e2-727df6bfb0ab">
<img width="1007" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/adeabfce-2cf2-499f-a7f0-703bda8234f6">
<img width="1100" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/ea44cedc-d23f-4d57-8660-d294296f6cb2">
<img width="1190" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/27599f09-bb71-4831-8207-0618e9d286c2">
<img width="1045" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/410064d3-7707-4f39-bab1-b74a665b7df4">
<img width="1202" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/4f2bb125-a65b-49c6-9ed8-9bcf605b6521">
<img width="1157" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/5a3fb8e4-5f3b-4100-aa0b-be9c149999b1">
<img width="1151" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/5bd03e85-dcd9-4ea2-94fd-b36caa86ee6f">
<img width="1096" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/168e919a-69ff-473e-84ef-812da46a1e74">


### ChatGPT RIKSARKIVETS "tillgänglighet av metadata"
* https://chatgpt.com/share/56bf5f0b-5878-4ebf-8fec-9429996736a6

<img width="1172" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/9a4d8228-269f-4a45-81e0-ec0c20bf37f9">

<img width="1104" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/6a004a56-3cba-430c-b7a1-6fce9b0ab30e">

<img width="1057" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/a2d34a40-4bff-42c7-8387-8459b9975c3b">

<img width="916" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/e43bf6db-3322-4484-9912-54a3fc3bc5af">

<img width="870" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/f3bb5aca-ff4f-4b9a-9656-1f076de6192a">

<img width="908" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/6f08079a-5451-4654-8d2c-fd14e7e3ffa7">

-----
Länkar från ChatGPT Github 

* #17 
* [GitHub salgo60/Svenskaforsamlingar/issues/7](https://github.com/salgo60/Svenskaforsamlingar/issues/7)) "Riksarkivet SBL: Släktartiklar saknar persistenta identifierare för personerna i biografierna"

**Comment by salgo60** [comment]
@DavidHaskiya kommer några från Riksarkivet att vara med på fredagens [TDM & AI Conference 2024](https://www.su.se/department-of-law/calendar/tdm-ai-conference-2024-1.734136) som man kan snacka metadata med

Känns som vi aldrig kommer framåt utan [publika backloggar och vettig helpdesk #3](https://github.com/salgo60/Svenskaforsamlingar/issues/3)

<img width="821" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/f8f10e43-fbd6-479e-98f2-4ba609ac3dec">

**Comment by salgo60** [comment]
chatGPT [vad Riksarkivet behöver göra](https://chatgpt.com/share/56bf5f0b-5878-4ebf-8fec-9429996736a6)

<img width="980" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/6a2930b8-3a37-40df-806c-59c84930b450">

<img width="976" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/349bff19-a213-4624-bb7b-cb7c0f8d697a">

<img width="941" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/35d97efa-b18f-450d-a3ce-a4824c61112a">

<img width="1005" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/38269ab8-a231-4273-86ff-52a4d2d5801e">

<img width="951" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/3d1327d9-9f51-470a-a4d1-fef79c351753">

<img width="927" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/3a4c916c-aad0-490d-803e-e94b0bb07c8a">

<img width="956" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/3b3d3215-bf8e-47f8-b0fc-cfb0fdfd0aca">

<img width="928" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/41e644bf-56d0-40d0-960f-ed672ab148c9">

<img width="863" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/2422a00a-92fd-45a5-9352-37ccfb86f53e">

<img width="875" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/d073e871-ed92-4134-a18b-bc490396cca2">

<img width="887" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/fe685cb7-f93c-4e19-88e7-2a1c20255200">

<img width="753" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/d6d7a478-52e6-4ad0-89a9-3868506ba6eb">

**Comment by salgo60** [comment]
* [chatGPT](https://chatgpt.com/share/56bf5f0b-5878-4ebf-8fec-9429996736a6)

<img width="754" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/39239726-0db7-42f0-901d-bcc298144151">

<img width="988" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/05258fb1-b58e-4edc-bbea-4f86249b8b42">

<img width="1037" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/738b4a51-3890-427e-abf9-7a3c7a96a510">

<img width="850" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/40089d83-6352-4395-a046-08817d47f314">
