### ISSUE TITLE
Feedback dataset organisationer

### ISSUE THREAD

**Issue by salgo60** [Riksarkivet/dataplattform#23]
Jag efterlyser backlogs med metadataskuld om vi skall röra oss framåt [issue #24](https://github.com/salgo60/Svenskaforsamlingar/issues/24)

**Exempel på lesson learned som borde delas så fler vet utmaningen** Vi testade att köra openrefine för 6 månaders sedan och försökte matcha Riksarkivets dataset med Wikidata endast 

https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/issues/10#issuecomment-1864959098

----

Det är mycket "gegga" som scoutkårer och det är lite för lite bra info hos Riksarkivet

1. jag körde Open Refine automatch

<img width="1253" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/b91d7373-ef90-49d0-887c-f477dfa02322">

2. sedan gick igenom 800 stycken för hand och kolla när flera alternativ var föreslagna

3. tar du exempel Torpshamra så finns det massa Torpshamra i Wikidata men ofta är det orter, museer som gar artikel....

<img width="1253" alt="image" src="https://github.com/perrohdin/Bildhistoria-Masterdata-och-Wikidata/assets/14206509/a0e38727-95aa-4dba-89a7-5e55f8c848b2">

4. att modulera organisationer över tid dvs. koncern / vilka namn byten som sker och vilka som köps upp kan vara svårt och tror wikipedia folk mer leker med influencers och adel gubbar....

### Lesson learned
att koppla "samma som" är även för enkla saker som personer/bolag kostsamt.

**Comment by salgo60** [comment]
Bra att dela men FB skalar inte utan använd Wikidata eller bygg ett eget WD

![image](https://github.com/Riksarkivet/dataplattform/assets/14206509/3cf76822-8076-436c-8b4f-4ea86812c010)

Vi ser på Wikidata att Sveriges kulturarv är mycket klippa klistra mellan olika datasilos och ser inte heller att källor används på ett proffsigt maskinläsbart sätt dvs. enormt svårt att förstå trovärdighet hos presenterat data [#167 Provenance i maskinläsbar form](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/167)

**Comment by salgo60** [comment]
## exempel där tydlighet vad som skall levereras gör att vi slipper dubbelarbete

![image](https://github.com/Riksarkivet/dataplattform/assets/14206509/e7c73c3e-8a54-4f3e-aa05-58f47234049b)

### Projekt Runeberg

Min tanke ett Riksarkiv som delar sina planer gör även att Runeberg springer åt rätt håll idag blir det bara datasilos

Skall kulturarvet ta steget till bra metadata och länkade data så behövs att alla begrepp som används kopplas ihop...

Min lösning skrev jag ned 2020 i "[The Magnus list](https://m.wikidata.org/wiki/User:Salgo60/ExternalIdentifiers)"

![image](https://github.com/Riksarkivet/dataplattform/assets/14206509/be486a33-e7f3-417b-af9d-361bdb25eaba)

**Comment by Abbe98** [comment]
@salgo60 ditt spam här gör det bara svårare för oss som faktiskt vill följa, använda och förbättra Riksarkivets dataplattform.

**Comment by salgo60** [comment]
@Abbe98  Förklara hur vi får fart på kulturarvet känns som inga ställer frågor till Riksarkivet och Riksarkivet stänger allt... så det är inte så mycket att följa... alla får pengar skattepengar men inga verkar jobba ihop...
* [Riksarkivet SBL Projekt på drift - för 62 år sedan var alla överens om att längre än 30 år till fick det inte ta](https://github.com/salgo60/Svenskaforsamlingar/issues/46)

Så länge man inte jobbar ingenjörsmässigt så kommer dom inte framåt är min tro....

Den produkt som Riksarkivet levererar verkar inte ens forskarna vilja ha utan väljer data från en hobbysite som Wikidata se SWERIKS

**Comment by Abbe98** [comment]
@salgo60 snack snack. Sluta fylla mina notifikationer med strunt.

**Comment by salgo60** [comment]
@Abbe98 berätta gärna vad du gjort hos Riksarkivet så vi andra förstår vart dom är på väg...

----
Problemet jag belyser med Riksarkivets data om organisationer är att 
* folk vill ha bra data ex. Bildhistoria
* det snackas en hel del att man kan köra Open Refine och tvätta data... här funkar inte det med Wikidata för att där finns inte bra organisations data historiskt
* att skall data bli bra så tvätta det vid källan vi kan inte gissa...

Nu skrivs det lite på FB om olika saker men det blir bara rörigt det måste till backloggar och en vilja att leverera bra data... LLM behöver data med bra kvalitet...

**Comment by DavidHaskiya** [comment]
Detta är en issue-board för Riksarkivets APIer. Inte för öppna dataset eller allmänt tyckande. Issuen stängs.
