### ISSUE TITLE
Arkivbildare upphov

### ISSUE THREAD

**Issue by salgo60** [Riksarkivet/dataplattform#3]
* Alfred Nobels arkiv **[SE/RA/720020/01](https://sok.riksarkivet.se/nad?Sokord=Alfred+Nobel&EndastDigitaliserat=false&BegransaPaTitelEllerNamn=false&lk=Ladda+kategorier&AvanceradSok=False&typAvLista=Standard&page=1&postid=Arkis+3ee28a56-9b89-11d5-a701-0002440207bb&tab=post&FacettState=undefined%3ac%7c&s=Balder)**
  * har Arkivbildare/upphov [Nobel, Alfred B. (1833-10-21 – 1896-12-10)](https://sok.riksarkivet.se/nad?Sokord=Alfred+Nobel&EndastDigitaliserat=false&BegransaPaTitelEllerNamn=false&lk=Ladda+kategorier&AvanceradSok=False&typAvLista=Standard&page=1&postid=ArkisRef+SE%2fRA%2f7888&tab=post&FacettState=undefined%3ac%7c&type=2&s=Balder)
  
 <img width="605" alt="image" src="https://user-images.githubusercontent.com/14206509/169248854-2ca6b0d0-f3d8-4eba-83ab-d8af53e6a773.png">
 
Tittar jag på dom "skolarkiv" jag matchat med en skola på WD så tycker jag det saknas _Arkivbildare/upphov_ men i exempelvis [Stockholms Stadsarkivets Skolregister](https://sok.stadsarkivet.stockholm.se/Databas/skolregistret/Sok) kan en skola peka på flera arkiv ex. [Kungsholms lägre elementarläroverk](https://sok.stadsarkivet.stockholm.se/Databas/skolregistret/Visa/kungsholms-lagre-elementarlaroverk/35500d81-9cdf-4b1c-b08f-45da92d3ceec) / WD [Q112030273](https://www.wikidata.org/wiki/Q112030273#P9493?uselang=sv) / Riksarkivet [SE/SSA/0148](https://sok.riksarkivet.se/nad?postid=Arkis%2012047f28-5d24-425a-8037-45398c408796) , [SE/SSA/0316](https://sok.riksarkivet.se/nad?postid=Arkis%20cf5fedd1-8ddb-445f-b9ce-4873edd3cebc) 

<img width="931" alt="image" src="https://user-images.githubusercontent.com/14206509/169251361-c2884615-14ab-4345-a9e2-55d69ef1ffe9.png">

* spontant så känns det som det skulle vara snyggare i Wikidata att vi för en skola kan peka på motsvarande objekt hos NAD för skolan och sedan under [Property:P9493](https://www.wikidata.org/wiki/Property:P9493) "_Arkiverad hos"_ peka på ert arkiv
  * hur skolor skall se ut i WD är inte 100 bestämt men tittar vi på SCB så delar dom upp i [skolenheter](https://www.scb.se/lamna-uppgifter/undersokningar/Skolenhetsregistret/) som vi i [WD sedan kopplar till skolor](https://www.wikidata.org/wiki/Wikidata:WikiProject_Sweden/Schools#School_units)
`a single school can be made up of on or more school units
`

**Fråga** är det en slump att det är olika eller hur tänker ni och hur är er målbild?

* WD ref till denna frågeställning [Wikidata_talk:WikiProject_Sweden](https://www.wikidata.org/wiki/Wikidata_talk:WikiProject_Sweden/Schools#Strukturen_hos_NAD)

**Comment by salgo60** [comment]
Hittade en skola som organisation [WD Q10499505](https://www.wikidata.org/wiki/Q10499505?uselang=sv#P9713) = [SE/GLA/2286](https://sok.riksarkivet.se/agent/9mmmKigRrH6xqG3GjpvwY3) där även relationen _efterföljare_ finns ex. "Mathilda Halls flickskola" WD [Q10578335](https://www.wikidata.org/wiki/Q10578335?uselang=sv) NAD [SE/GLA/2268](https://sok.riksarkivet.se/nad?postid=Arkis+52300c15-9bca-11d5-bbd1-00d0b73e7a8b&s=Balder) lite udda att den sägs i NAD vara en myndighet


<img width="749" alt="image" src="https://user-images.githubusercontent.com/14206509/169289912-a40731ea-924a-4957-bab4-bb9d6f931f04.png">

**Comment by salgo60** [comment]
<img width="804" alt="image" src="https://user-images.githubusercontent.com/14206509/169511467-be2743b9-af17-40f7-923d-f3a15d774c93.png"> 

* nedan samma som WD [Q10578335](https://www.wikidata.org/wiki/Q10578335?uselang=sv)

<img width="746" alt="image" src="https://user-images.githubusercontent.com/14206509/169511618-db474f58-b51d-40c0-8640-8301efbf2ce4.png">

**Comment by nilsw-ra** [comment]
Arkivbildare/upphov finns inte registrerat på alla arkiv (och därmed saknas också auktoritetsposter för många organisationer och personer). Som så mycket annat när det gäller fullständighet och konsekvens i data är det en fråga om prioriteringar av knappa resurser, så jag kan inte utlova någon insats för att komplettering.

**Comment by nilsw-ra** [comment]
Vad gäller kategoriseringen av skolan (där det faktiskt finns en auktoritetspost) som myndighet tror jag det kan vara korrekt. Givet den lista med auktoritetstyper som finns i NAD räknas troligen offentliga (dvs de som nu är kommunala) skolor som myndighet.

Så här ser listan ut:

Myndighet (upphörd)
Myndighet
Arkivinstitution
Enhet inom myndighet (upphörd)
Enhet inom myndighet
Depå
Organisation (upphörd)
Organisation
Organisatorisk enhet (upphörd)
Organisatorisk enhet
Person
Person (oident.)
Familj
Systemauktoritet
Alla auktoritetstyper
Ämnesord person/inst ARKIS1
Kongress
Organ med offentligt uppdrag (upphört)
Organ med offentligt uppdrag
Lokal upphovsman (Kartia)

**Comment by salgo60** [comment]
> Arkivbildare/upphov finns inte registrerat på alla arkiv (och därmed saknas också auktoritetsposter för många organisationer och personer). Som så mycket annat när det gäller fullständighet och konsekvens i data är det en fråga om prioriteringar av knappa resurser, så jag kan inte utlova någon insats för att komplettering.

Tackar det intressanta för oss är att förstå datamodellen i de olika arkiven finns det dokumenterat skulle det underlätta...

Inser nu att vi inte förstod denna struktur 2017 då vi skapade [kopplingen mellan Sveriges alla församlingar och kyrkoarkiven](https://github.com/salgo60/Svenskaforsamlingar)... nu har vi skrivit massa kod som kopplar detta till sv:Wikipedia så nu tvekar jag vi vågar/orkar ändra det 😢  --> [#metadatadebt](https://twitter.com/salgo60/status/1237262589341687809)
* ändring [2017 på Söderala församling](https://www.wikidata.org/w/index.php?uselang=sv&title=Q10688470&type=revision&diff=698001182&oldid=484504644) --> WD [Q10688470](https://www.wikidata.org/wiki/Q10688470?uselang=sv) borde inta ha arkivet samma som utan peka på er "organisation" för församlingen gissar jag....
  * nu har även Tora projektet [T233275](https://phabricator.wikimedia.org/T233275) en koppling samma som Wikidata där Wikidata missat NAD strukturen....
  * GITHUB repository [salgo60/Svenskaforsamlingar](https://github.com/salgo60/Svenskaforsamlingar) där jag försökte hålla koll på kyrkoarkiv
  * Arkiv Digital har integrerat med Wikidata [T199907](https://phabricator.wikimedia.org/T199907) och hämtar koordinater för var församlingar ligger via NAD
  * Family Search använder Wikidata [T200515](https://phabricator.wikimedia.org/T200515) för att "studsa vidare till Open Street map, NAD, Wikipedia... (verktyg [hub.toolforge.org](https://hub.toolforge.org/) --> syntax se nedan )
     * Exempel [Söderala_Parish,_Gävleborg,_Sweden_Genealogy](https://www.familysearch.org/en/wiki/S%C3%B6derala_Parish,_G%C3%A4vleborg,_Sweden_Genealogy)
        * har länk Open Street Map https://tools.wmflabs.org/hub/P5324:SE/HLA/1010201?property=P625
           *  där [P625 är koordinat](https://www.wikidata.org/wiki/Property:P625?uselang=sv) i WD och [P5324](https://www.wikidata.org/wiki/Property:P5324?uselang=sv) är NAD
        * har länk [SCB Regina](https://regina.scb.se/) som har administrativa gränser men tror jag ruttnat (dom saknar bra helpdesk som ger tydliga svar fick [indikation vi annan kanal](https://phabricator.wikimedia.org/T266870)) https://tools.wmflabs.org/hub/P5324:SE/HLA/1010201?property=P778
           *  där [P778 är Församlingskod](https://www.wikidata.org/wiki/Property:P778?uselang=sv)
         * där P5324 kan skickas in och vi pekar på [var det finns i NAD ex.  hub/P5324:SE/HLA/1010201?property=P5324](https://tools.wmflabs.org/hub/P5324:SE/HLA/1010201?property=P5324)           

Så nu när vi kanske förstår strukturen av NAD känns det som vi inte vågar städa upp WD och det jag nu ser som #[metadatadebt](https://twitter.com/hashtag/metadatadebt?src=hashtag_click) gissar att någon datamodell hos NAD dag 0 skulle gjort att vi gjorde mer rätt.... 
  
  * ser samma problem idag med  [Stockholms stads skolregister](https://sok.stadsarkivet.stockholm.se/Databas/skolregistret/Sok) som är väldigt hafsigt med att dom blandar [skola](https://sok.stadsarkivet.stockholm.se/Databas/skolregistret/Visa/carlgrenska-waldorfgymnasiet/bf4aeb94-88b6-4224-b4bd-002dd8a79ed4), [skolenhet](https://www.scb.se/vara-tjanster/oppna-data/api-for-skolenhetsregistret/), [rektorsområde](https://sok.stadsarkivet.stockholm.se/Databas/skolregistret/Sok?sidindex=0&skolans-namnalt-namn=Rektorsomr%25c3%25a5de), beskrivning av ord (ex. [Typskola](https://sok.stadsarkivet.stockholm.se/Databas/skolregistret/Visa/typskola--typskolor/b6793b92-f2fc-4a99-be4b-b12cd6108672?sidindex=0&skolans-namnalt-namn=+typskola+)) dvs. det känns som dom saknar en tanke med en datamodell utan bara stoppar in allt dom kommer på --> svårt att skapa kopplingar och automatisera.....
  
 **Sammanfattning Lesson learned**:  data som presenteras och skall konsumeras/ kopplas ihop med andra bör nog även ha en datamodell så vi slipper ännu mera otydlighet och #[metadatadebt](https://twitter.com/hashtag/metadatadebt?src=hashtag_click) som jag tycker mig se vi har nu... vi försöker reda ordning bättre i detta med svenska skolor se projekt ytan [Wikidata:WikiProject_Sweden/Schools](https://www.wikidata.org/wiki/Wikidata:WikiProject_Sweden/Schools)... gissar att ingen städar upp församlingsarkiven i WD vilket är lite sorgligt.... Lite synd att inte [DIGG](https://www.digg.se/) eller [DIGISAM](https://www.digisam.se/) lyfter saker som detta så alla drar i samma riktning....

**Comment by salgo60** [comment]
> Vad gäller kategoriseringen av skolan (där det faktiskt finns en auktoritetspost) som myndighet tror jag det kan vara korrekt. Givet den lista med auktoritetstyper som finns i NAD räknas troligen offentliga (dvs de som nu är kommunala) skolor som myndighet.
> 

Nja jag tycker nog man skall städa sitt data (det blir aldrig perfekt) och ha en [backlog med en städaktivitet som sköts av en produktägare](https://www.youtube.com/watch?v=502ILHjX9EE) som är öppen så vi förstår vart ni vill. Min känsla är att **data ruttnar** och det är viktigt att jobba med det jag kallar [metadatadebt](https://twitter.com/hashtag/Metadatadebt?src=hashtag_click)  .... drömmen vore om Wikidata kunde hjälpa till och vara så bra att ni litade på WIkidata ...

* [tweet](https://twitter.com/salgo60/status/1237262589341687809?s=20&t=FIsnCA0qUEjYmm6TxjbwWw)

<img width="620" alt="image" src="https://user-images.githubusercontent.com/14206509/169643015-58ab3360-d7c4-4603-827d-e9a3dc17bd67.png">

**Comment by salgo60** [comment]
Nu diskuterar vi på [sv:Wikipedia att koppla ihop oss med RAÄ](https://sv.wikipedia.org/wiki/Wikipedia:Bybrunnen#Bra_steg_fram%C3%A5t) vore enormt intressant att veta hur Riksarkivet tänker att vi skall jobba ihop och hur ni jobbar ihop med andra som RAÄ

* [ Wikipedia:Bybrunnen](https://sv.wikipedia.org/wiki/Wikipedia:Bybrunnen#Bra_steg_fram%C3%A5t)

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/14206509/173344905-b9ac92e2-2a1b-42a9-89bd-28506f2e30c2.png">

**Comment by nilsw-ra** [comment]
Lite kort om vad vi gör och planerar på Riksarkivet, vet inte om det besvarar frågan men det är vad jag kan bidra med just nu:

1. Som du säkert sett så publicerar vi en del "curated" material på Wikimedia-plattformarna, intressanta digitiserade arkivobjekt som vi skapar Wikidata-objekt för och laddar upp högupplöst bild på Wikimedia Commons (gamla kartor, fartygsritningar mm).
2. Vi planerar ett sök-API motsvarande fritextsökning och facetterad filtrering i söktjänsten. Vi har en utvecklingsomgång under hösten, jag hoppas det kan komma med då och bli tillgängligt nästa år.
3. I samband med sök-APIet kommer vi också att publicera data om de enskilda posterna som länkade data. I väntan på att standarden [Records in Context](https://www.ica.org/en/records-in-contexts-ontology) skall bli färdig kommer vi tills vidare att modellera RDF-representationen med befintliga standardvokabulärer (DC, SKOS, schema.org).

**Comment by salgo60** [comment]
**Tackar Tackar Tackar** jag är inte mycket på Wikipedia så jag har missat det.... ramlade bara in i en [diskussion idag](https://sv.wikipedia.org/wiki/Special:Bidrag/Salgo60)

Vore enormt bra om saker som detta kunde formaliseras så den intresserade kan följa detta och inspireras...  kanske skriva en [blänkare på Bybrunnen.](https://sv.wikipedia.org/wiki/Wikipedia:Bybrunnen)... och bra vore om 
 ni giganter springer åt samma håll så även ni hittar bra sätt att skapa data som fungerar ihop med dom andra se [test #104](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/104)
 
 Se exempel när jag kollar på hur Alvin, Riksarkivet, SKBL... [beskriver yrken digitalt](https://github.com/salgo60/HISCOKoder) där alla "uppfinner hjulet igen" och skapar data som inte kopplas mellan varandra....

#[linkeddataneedslinkedpeople](https://twitter.com/hashtag/linkeddataneedslinkedpeople?src=hash)
