### ISSUE TITLE
Arkiv / Släktforsknings user case

### ISSUE THREAD

**Issue by salgo60** [Riksarkivet/dataplattform#5]
delar min vaga vision här apropå DIGG [diskussions forum om URI:er](https://community.dataportal.se/post/1890)

Min tro är att skall vi peka på vilket arkiv en person finns i så skall det vara enkelt att hitta dom personer som finns i samma fysiska arkiv
* I Wikidata har vi idag följande egenskaper kopplade till Riksarkivet
   * [Property:P3217](https://www.wikidata.org/wiki/Property:P3217) - "Riksarkivet SBL" 21 000 kopplingar - kan vara komplett för personer men vi gissar och webscrapar se [Notebook](https://github.com/salgo60/open-data-examples/blob/master/SBL.ipynb)
   * [Property:P4820](https://www.wikidata.org/wiki/Property:P4820) - "TORA-ID" 676 kopplingar - har bra kopplingar församlingar - [SPARQL federation skillnad](https://tora.entryscape.net/snorql/?query=PREFIX+wd%3A+%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2F%3E%0D%0APREFIX+wdt%3A+%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fdirect%2F%3E%0D%0ASELECT+DISTINCT+%3Finstance+%3FTORA_label+%3FTORA_province_name+%3FwdLabel+%3FwdAdminLabel++%3FTORA_parishcode+%3FTORA_wd+%3FTORA_wd+%3FWD+%3FWDsame+%3Fitem+%3FWiki%0D%0AWHERE+%7B+%3Finstance+a+%3Chttps%3A%2F%2Fdata.riksarkivet.se%2Ftora%2Fschema%2FModernParish%3E.%0D%0A%3Finstance+skos%3AaltLabel+%3FTORA_label+.%0D%0AOPTIONAL+%7B%3Finstance+tora%3Aprovince_name+%3FTORA_province_name%7D%0D%0A%3Finstance+tora%3Aparishcode+%3FTORA_parishcode+.%0D%0A%3Finstance++rdfs%3AseeAlso+%3FTORA_wduri+.%0D%0ABIND+%28REPLACE%28str%28%3FTORA_wduri%29%2C%22https%3A%2F%2Fwww.wikidata.org%2Fwiki%2F%22%2C%22%22%29+AS+%3FTORA_wd%29.%0D%0ABIND+%28REPLACE%28str%28%3Fitem%29%2C%22http%3A%2F%2Fwww.wikidata.org%2Fentity%2F%22%2C%22%22%29+AS+%3FWD%29.%0D%0A++BIND%28%0D%0A+++IF%28%3FWD+%3D+%3FTORA_wd%2C+%22Y%22%2C++%22N%22%29%0D%0A++++AS+%3FWDsame%29.%0D%0ASERVICE+%3Chttps%3A%2F%2Fquery.wikidata.org%2Fsparql%3E+%7B+%0D%0A++++%3Fitem+wdt%3AP31+wd%3AQ1523821%3B+wdt%3AP777+%3FTORA_parishcode+.+%0D%0A%09OPTIONAL+%7B%0D%0A%09%09%3Fitem+rdfs%3Alabel+%3FwdLabel.%0D%0A%09%09FILTER%28LANG%28%3FwdLabel%29+%3D+%22sv%22%29.%0D%0A%09%7D%0D%0A+++++++OPTIONAL+%7B+%0D%0A+++++++++++++++%3Fitem+wdt%3AP131+%3FWDAdmin.%0D%0A+++++++++++++++%3FWDAdmin+wdt%3AP31+wd%3AQ193556.%0D%0A%09%09%3FWDAdmin+rdfs%3Alabel+%3FwdAdminLabel.%0D%0A%09%09FILTER%28LANG%28%3FwdAdminLabel%29+%3D+%22sv%22%29.%0D%0A%09%7D%0D%0A%7D%0D%0AFILTER+%28%28+STRSTARTS%28str%28%3FTORA_wduri%29%2C+%22https%3A%2F%2Fwww.wikidata.org%2Fwiki%2F%22%29%29+%26%26+%3FWDsame+%3D+%22N%22+%29%0D%0A%7D+order+by++%3FTORA_label) / [alla](https://tora.entryscape.net/snorql/?query=PREFIX+wd%3A+%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2F%3E%0D%0APREFIX+wdt%3A+%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fdirect%2F%3E%0D%0ASELECT+DISTINCT+%3Finstance+%3FTORA_label+%3FTORA_province_name+%3FwdLabel+%3FwdAdminLabel++%3FTORA_parishcode+%3FTORA_wd+%3FTORA_wd+%3FWD+%3FWDsame+%3Fitem+%3FWiki%0D%0AWHERE+%7B+%3Finstance+a+%3Chttps%3A%2F%2Fdata.riksarkivet.se%2Ftora%2Fschema%2FModernParish%3E.%0D%0A%3Finstance+skos%3AaltLabel+%3FTORA_label+.%0D%0AOPTIONAL+%7B%3Finstance+tora%3Aprovince_name+%3FTORA_province_name%7D%0D%0A%3Finstance+tora%3Aparishcode+%3FTORA_parishcode+.%0D%0A%3Finstance++rdfs%3AseeAlso+%3FTORA_wduri+.%0D%0ABIND+%28REPLACE%28str%28%3FTORA_wduri%29%2C%22https%3A%2F%2Fwww.wikidata.org%2Fwiki%2F%22%2C%22%22%29+AS+%3FTORA_wd%29.%0D%0ABIND+%28REPLACE%28str%28%3Fitem%29%2C%22http%3A%2F%2Fwww.wikidata.org%2Fentity%2F%22%2C%22%22%29+AS+%3FWD%29.%0D%0A++BIND%28%0D%0A+++IF%28%3FWD+%3D+%3FTORA_wd%2C+%22Y%22%2C++%22N%22%29%0D%0A++++AS+%3FWDsame%29.%0D%0ASERVICE+%3Chttps%3A%2F%2Fquery.wikidata.org%2Fsparql%3E+%7B+%0D%0A++++%3Fitem+wdt%3AP31+wd%3AQ1523821%3B+wdt%3AP777+%3FTORA_parishcode+.+%0D%0A%09OPTIONAL+%7B%0D%0A%09%09%3Fitem+rdfs%3Alabel+%3FwdLabel.%0D%0A%09%09FILTER%28LANG%28%3FwdLabel%29+%3D+%22sv%22%29.%0D%0A%09%7D%0D%0A+++++++OPTIONAL+%7B+%0D%0A+++++++++++++++%3Fitem+wdt%3AP131+%3FWDAdmin.%0D%0A+++++++++++++++%3FWDAdmin+wdt%3AP31+wd%3AQ193556.%0D%0A%09%09%3FWDAdmin+rdfs%3Alabel+%3FwdAdminLabel.%0D%0A%09%09FILTER%28LANG%28%3FwdAdminLabel%29+%3D+%22sv%22%29.%0D%0A%09%7D%0D%0A%7D%0D%0A%7D+order+by++%3FTORA_label) - task [T233275](https://phabricator.wikimedia.org/T233275)  
   * [Property:P5324](https://www.wikidata.org/wiki/Property:P5324) - "Nationell Arkivdatabas Referenskod" 6700 kopplingar
   * [Property:P9713](https://www.wikidata.org/wiki/Property:P9713) - "Nationell Arkivdatabas agent-id" 1000 kopplingar - borde vara lika många som P5324 - **finns API? eller data dump...**

   
**User case A:** Som släktforskare vill jag enkelt kunna hitta saker relaterade till den aktivitet jag gör så man kan "skörda fler frukter....

Den släktforskning jag tror mig se med ny teknik är att man "jobbar ihop mer" och försöker lösa flera utmaningar när man är i ett arkiv,,,, och kanske kan få ledtrådar av vad andra gjort....
* exempel
   * [Svenskt Porträttarkiv (SPA)](https://portrattarkiv.se/about) Omar scannar in allt han ser 900 000 andra skriver API:er och jag gör en 3 klickslösning i Wikipedia som läser ett kategori namn och gör en sökning i SPA [GITHUB](https://github.com/salgo60/spa2Commons) [video](https://www.youtube.com/watch?v=dQuoJOC3eSY) [14000 bilder hämtade](https://commons.wikimedia.org/wiki/Category:Uploaded_with_spa2Commons)
   * att är man på Norra Begravningsplatsen och intresserad av kvinnoforskning så vandrar man runt på alla gravar för kvinnor som finns i SKBL [blogpost](https://minancestry.blogspot.com/2018/03/svenskt-kvinnobiografiskt-lexikon.html)  se [liknande för SBL ](http://minancestry.blogspot.com/2017/05/sbl-wikidata.html) --> [sökning SBL och Norra Begravningsplatsen](http://tinyurl.com/y9rfdsdm) --> **839 kopplingar**
       * [Norra begravningsplatsen - SBL - Spotify](https://query.wikidata.org/embed.html#%23%20Query%20Find%20in%20WikiData%20people%20with%20Place%20of%20Burial%20Q252312%20Norra%20Begravningsplatsen%0A%23%20and%20SBL%0A%23%20Show%20Wikitree%20ID%2C%20Find%20A%20Grave%20ID%20and%20if%20picture%20of%20the%20grave%20exist%0A%23%20version%202%20Google%20map%20link%0A%23defaultView%3AMap%0Aselect%20distinct%20%20%3FSpotify%20%3Fperson%20%3FpersonLabel%20%20%3FpersonDescription%20%20%3Fgraveplot%20%20%3Fpic%20%3Fcoord%20%3FpicGrave%20%3FgroupLabel%20%28%3FgroupLabel%20as%20%3Flayer%29%0A%28IRI%28CONCAT%28%22https%3A%2F%2Fwww.google.com%2Fmaps%2F%3Fq%3D%22%2C%20STR%28%3Flat%29%2C%20%22%2C%22%2C%20STR%28%3Flon%29%29%29%20AS%20%3FGoogleMap%29%20%3FSBL%20%7B%0A%7B%0A%09%3Fperson%20wdt%3AP119%20wd%3AQ252312%3B%20%23Place%20of%20burial%0A%20%20%20%20%20%20%20%20%20%20%20%20p%3AP119%20%5B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20pq%3AP965%20%3Fgraveplot%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20pq%3AP625%20%3Fcoord%3B%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20pqv%3AP625%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgeoLatitude%20%3Flat%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgeoLongitude%20%3Flon%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D.%20%20%20%20%20%20%20%20%0A%20%20%20%7B%20%3Fperson%20wdt%3AP3217%20%3FSBLID%20.%7D%20%09%09%09%09%09%09%23%20SBL%0A%20%20%20%7B%20%3Fperson%20wdt%3AP1902%20%3FSpotifyID%20.%7D%20%09%09%09%09%09%23%20SBL%0A%20%20%20OPTIONAL%20%7B%3Fperson%20wdt%3AP569%20%3Fbirthdate%7D%20%0A%20%20%20OPTIONAL%7B%20%3Fperson%20wdt%3AP18%20%3Fpic%20.%7D%20%09%09%09%09%09%23%20If%20we%20have%20an%20illustration%0A%20%20%20OPTIONAL%7B%20%3Fperson%20wdt%3AP1442%20%3FpicGrave%20.%7D%20%09%09%09%23%20If%20we%20have%20a%20picture%20of%20the%20grave%0A%20%20%20BIND%20%28URI%28CONCAT%28%22https%3A%2F%2Fsok.riksarkivet.se%2Fsbl%2FPresentation.aspx%3Fid%3D%22%2C%3FSBLID%29%29%20AS%20%3FSBL%29%0A%20%20%20BIND%20%28URI%28CONCAT%28%22https%3A%2F%2Fopen.spotify.com%2Fartist%2F%22%2C%3FSpotifyID%29%29%20AS%20%3FSpotify%29%0A%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%3Farticle%20schema%3Aabout%20%3Fperson%20.%0A%20%20%20%20%20%20%3Farticle%20schema%3AinLanguage%20%22sv%22%20.%0A%20%20%20%20%20%20%3Farticle%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fsv.wikipedia.org%2F%3E%20.%0A%20%20%20%20%7D%0A%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%3Farticle%20schema%3Aabout%20%3Fperson%20.%0A%20%20%20%20%20%20%3Farticle%20schema%3AinLanguage%20%22en%22%20.%0A%20%20%20%20%20%20%3Farticle%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fsv.wikipedia.org%2F%3E%20.%0A%20%20%20%20%7D%0A%23%20%20%20OPTIONAL%20%7B%20%3Fperson%20wdt%3AP21%20%3Fgroup%20.%7D%20%09%09%09%23%20Gender%20in%20Layer%0A%20%20%20OPTIONAL%20%7B%20%3Fperson%20wdt%3AP106%20%3Fgroup%20.%7D%20%09%09%09%23%20Occupation%20in%20Layer%0A%0A%7D%20%20%20%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22sv%22%2C%22en%22%7D%0A%20%7D%0AOrder%20by%20%3FpersonLabel) - **172 personer**
          * SBL optional --> [348 personer](https://query.wikidata.org/embed.html#%23%20Query%20Find%20in%20WikiData%20people%20with%20Place%20of%20Burial%20Q252312%20Norra%20Begravningsplatsen%0A%23%20and%20SBL%0A%23%20Show%20Wikitree%20ID%2C%20Find%20A%20Grave%20ID%20and%20if%20picture%20of%20the%20grave%20exist%0A%23%20version%202%20Google%20map%20link%0A%23defaultView%3AMap%0Aselect%20distinct%20%20%3FSpotify%20%3Fperson%20%3FpersonLabel%20%20%3FpersonDescription%20%20%3Fgraveplot%20%20%3Fpic%20%3Fcoord%20%3FpicGrave%20%3FgroupLabel%0A%28IRI%28CONCAT%28%22https%3A%2F%2Fwww.google.com%2Fmaps%2F%3Fq%3D%22%2C%20STR%28%3Flat%29%2C%20%22%2C%22%2C%20STR%28%3Flon%29%29%29%20AS%20%3FGoogleMap%29%20%3FSBL%20%7B%0A%7B%0A%09%3Fperson%20wdt%3AP119%20wd%3AQ252312%3B%20%23Place%20of%20burial%0A%20%20%20%20%20%20%20%20%20%20%20%20p%3AP119%20%5B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20pq%3AP965%20%3Fgraveplot%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20pq%3AP625%20%3Fcoord%3B%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20pqv%3AP625%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgeoLatitude%20%3Flat%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgeoLongitude%20%3Flon%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D.%20%20%20%20%20%20%20%20%0A%20%20%20OPTIONAL%20%7B%20%3Fperson%20wdt%3AP3217%20%3FSBLID%20.%7D%20%09%09%09%09%09%09%23%20SBL%0A%20%20%20%7B%20%3Fperson%20wdt%3AP1902%20%3FSpotifyID%20.%7D%20%09%09%09%09%09%23%20SBL%0A%20%20%20OPTIONAL%20%7B%3Fperson%20wdt%3AP569%20%3Fbirthdate%7D%20%0A%20%20%20OPTIONAL%7B%20%3Fperson%20wdt%3AP18%20%3Fpic%20.%7D%20%09%09%09%09%09%23%20If%20we%20have%20an%20illustration%0A%20%20%20OPTIONAL%7B%20%3Fperson%20wdt%3AP1442%20%3FpicGrave%20.%7D%20%09%09%09%23%20If%20we%20have%20a%20picture%20of%20the%20grave%0A%20%20%20BIND%20%28URI%28CONCAT%28%22https%3A%2F%2Fsok.riksarkivet.se%2Fsbl%2FPresentation.aspx%3Fid%3D%22%2C%3FSBLID%29%29%20AS%20%3FSBL%29%0A%20%20%20BIND%20%28URI%28CONCAT%28%22https%3A%2F%2Fopen.spotify.com%2Fartist%2F%22%2C%3FSpotifyID%29%29%20AS%20%3FSpotify%29%0A%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%3Farticle%20schema%3Aabout%20%3Fperson%20.%0A%20%20%20%20%20%20%3Farticle%20schema%3AinLanguage%20%22sv%22%20.%0A%20%20%20%20%20%20%3Farticle%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fsv.wikipedia.org%2F%3E%20.%0A%20%20%20%20%7D%0A%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%3Farticle%20schema%3Aabout%20%3Fperson%20.%0A%20%20%20%20%20%20%3Farticle%20schema%3AinLanguage%20%22en%22%20.%0A%20%20%20%20%20%20%3Farticle%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fsv.wikipedia.org%2F%3E%20.%0A%20%20%20%20%7D%0A%23%20%20%20OPTIONAL%20%7B%20%3Fperson%20wdt%3AP21%20%3Fgroup%20.%7D%20%09%09%09%23%20Gender%20in%20Layer%0A%20%20%20OPTIONAL%20%7B%20%3Fperson%20wdt%3AP106%20%3Fgroup%20.%7D%20%09%09%09%23%20Occupation%20in%20Layer%0A%0A%7D%20%20%20%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22sv%22%2C%22en%22%7D%0A%20%7D%0AOrder%20by%20%3FpersonLabel) - [Spotify men ej SBL](https://query.wikidata.org/embed.html#%23%20Query%20Find%20in%20WikiData%20people%20with%20Place%20of%20Burial%20Q252312%20Norra%20Begravningsplatsen%0A%23%20and%20SBL%0A%23%20Show%20Wikitree%20ID%2C%20Find%20A%20Grave%20ID%20and%20if%20picture%20of%20the%20grave%20exist%0A%23%20version%202%20Google%20map%20link%0A%23defaultView%3AMap%0Aselect%20distinct%20%20%3FSpotify%20%3Fperson%20%3FpersonLabel%20%20%3FpersonDescription%20%20%3Fgraveplot%20%20%3Fpic%20%3Fcoord%20%3FpicGrave%20%3FgroupLabel%0A%28IRI%28CONCAT%28%22https%3A%2F%2Fwww.google.com%2Fmaps%2F%3Fq%3D%22%2C%20STR%28%3Flat%29%2C%20%22%2C%22%2C%20STR%28%3Flon%29%29%29%20AS%20%3FGoogleMap%29%20%3FSBL%20%7B%0A%7B%0A%09%3Fperson%20wdt%3AP119%20wd%3AQ252312%3B%20%23Place%20of%20burial%0A%20%20%20%20%20%20%20%20%20%20%20%20p%3AP119%20%5B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20pq%3AP965%20%3Fgraveplot%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20pq%3AP625%20%3Fcoord%3B%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20pqv%3AP625%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgeoLatitude%20%3Flat%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AgeoLongitude%20%3Flon%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D.%20%20%20%20%20%20%20%20%0A%20%20%20minus%20%7B%20%3Fperson%20wdt%3AP3217%20%3FSBLID%20.%7D%20%09%09%09%09%09%09%23%20SBL%0A%20%20%20%7B%20%3Fperson%20wdt%3AP1902%20%3FSpotifyID%20.%7D%20%09%09%09%09%09%23%20SBL%0A%20%20%20OPTIONAL%20%7B%3Fperson%20wdt%3AP569%20%3Fbirthdate%7D%20%0A%20%20%20OPTIONAL%7B%20%3Fperson%20wdt%3AP18%20%3Fpic%20.%7D%20%09%09%09%09%09%23%20If%20we%20have%20an%20illustration%0A%20%20%20OPTIONAL%7B%20%3Fperson%20wdt%3AP1442%20%3FpicGrave%20.%7D%20%09%09%09%23%20If%20we%20have%20a%20picture%20of%20the%20grave%0A%20%20%20BIND%20%28URI%28CONCAT%28%22https%3A%2F%2Fsok.riksarkivet.se%2Fsbl%2FPresentation.aspx%3Fid%3D%22%2C%3FSBLID%29%29%20AS%20%3FSBL%29%0A%20%20%20BIND%20%28URI%28CONCAT%28%22https%3A%2F%2Fopen.spotify.com%2Fartist%2F%22%2C%3FSpotifyID%29%29%20AS%20%3FSpotify%29%0A%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%3Farticle%20schema%3Aabout%20%3Fperson%20.%0A%20%20%20%20%20%20%3Farticle%20schema%3AinLanguage%20%22sv%22%20.%0A%20%20%20%20%20%20%3Farticle%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fsv.wikipedia.org%2F%3E%20.%0A%20%20%20%20%7D%0A%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%3Farticle%20schema%3Aabout%20%3Fperson%20.%0A%20%20%20%20%20%20%3Farticle%20schema%3AinLanguage%20%22en%22%20.%0A%20%20%20%20%20%20%3Farticle%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fsv.wikipedia.org%2F%3E%20.%0A%20%20%20%20%7D%0A%23%20%20%20OPTIONAL%20%7B%20%3Fperson%20wdt%3AP21%20%3Fgroup%20.%7D%20%09%09%09%23%20Gender%20in%20Layer%0A%20%20%20OPTIONAL%20%7B%20%3Fperson%20wdt%3AP106%20%3Fgroup%20.%7D%20%09%09%09%23%20Occupation%20in%20Layer%0A%0A%7D%20%20%20%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22sv%22%2C%22en%22%7D%0A%20%7D%0AOrder%20by%20%3FpersonLabel) 176 personer
       * [SBL - Norra Begravningsplatsen - yrken](http://tinyurl.com/ycbmo5sp)
   
   <img width="861" alt="image" src="https://user-images.githubusercontent.com/14206509/185051965-699aacbf-ac99-4522-9025-25448d4d39ae.png">   
   
<img width="861" alt="image" src="https://user-images.githubusercontent.com/14206509/185067281-105023b0-75f9-4f27-ad70-bb59b59b4f44.png">

   **Vad behövs** enkelt kunna se vart fysiska arkiv finns så man kan besöka ett arkiv och ha med sig 20 kandidater för att leta i detta arkiv,....
   
   **User Case B:** att det finns semantiska kopplingar mellan plats i kyrkböcker och geografisk plats dvs. det skall kunna gå att hämta ut alla personer med ett "**nära avstånd**" mellan 2 släktträd där exempelvis 2 personer har DNA testat sig och enligt DNA testerna har ett släktskap men vi behöver "ledtrådar var i släktträdena det kan finnas en koppling" se [blogpost där dagens DNA forskning har nära avstånd men inte old school släktforskning](https://minancestry.blogspot.com/2020/06/kunskapsdatabaser-for-slaktforskning.html) (Youtube verkar tyvärr ta bort DNA videos eftersom dom tror det är rasism....)
   
   **Vad jag tror behövs** Kunna skicka in Kyrkboksreferensen ex. Bygdeå kyrkoarkiv, Lysnings- och vigselböcker, SE/HLA/1010025/E I/1 (1865-1894), bildid: [F0010296_00129](https://sok.riksarkivet.se/bildvisning/F0010296_00129#?c=&m=&s=&cv=128&xywh=-15%2C2321%2C2617%2C1996) -  är WD [Q5819424#P570](https://www.wikidata.org/wiki/Q5819424#P570)
      * vi har idag med [Arkiv DIgital 2018 kopplat NAD till Wikidata post se T199907](https://phabricator.wikimedia.org/T199907) för församlingen där koordinat finns för kyrkan 
         * tror samma bör göras med Riksarkivet **PLUS** skapa ett närhetsvärde som antal sidor mellan personer i samma kyrkbok, distans mellan församlingarnas kyrkor, finns man i en husförhörsbok X så borde man kunna via Linked data kunna hämta ut att man har en ättling som finns i ena släktträdet med en källa i en bok i samma församling och 10 år senare finns i det andra släktträdet en källa till en person i släktträd 2.... blir någon typ av "triangulering" i **oldschool släktforskning** där DNA släktforskningens väldigt strukturerade data får lite mer hjälp av traditionell kyrkoboksforskning eller åtminstone kanske en "[breadcrumb](https://en.wikipedia.org/wiki/Bread_crumbs#In_popular_culture)"

**Comment by nilsw-ra** [comment]
Jag stänger denna också då det inte är någon konkret felrapport eller förslag som direkt berör befintliga APIer. Jag kan dock notera följande:

- Kyrkoarkiv kommer, som andra arkivenheter, att exponeras som länkade data/RDF, med en första implementation under året
- Kyrkoarkiven har via arkivbildaren (organisationsauktoritet för församlingen) en koppling till en topografi-post för församlingen, vilket vi borde indexera för att kunna använda till en geografisk facett i sök-APIet som också är under utveckling
- Kyrkoarkiven har en koppling till den arkivinstitution där det fysiska arkivet finns, detta är dock bara en organisationsauktoritet utan topografisk koppling

**Comment by salgo60** [comment]
> * Kyrkoarkiven har en koppling till den arkivinstitution där det fysiska arkivet finns, detta är dock bara en organisationsauktoritet utan topografisk koppling

Gör som Arkiv Digital hämta den från WD se task [T199907](https://phabricator.wikimedia.org/T199907)
* vi fick ingen återkoppling av Arkiv Digital efteråt så antingen (vilket jag inte tror) var WD perfekt eller så diffar Arkiv DIgital med WD.... finns ju även församlingar som [Hovförsamlingen vars fysiska koppling kan diskuteras....](https://sv.wikipedia.org/wiki/Icke-territoriella_f%C3%B6rsamlingar)

* det jag tror man vill ha som saknas i WD är gränsar till.... det har vi för kommuner i [WD P47](https://www.wikidata.org/wiki/Q510010#P47)
  * skall man **börja med datadriven släktforskning** så är min erfarenhet att församlingar som gränsar till ens egen är kandidater till att leta i...
  
  <img width="1266" alt="image" src="https://user-images.githubusercontent.com/14206509/218394996-635e5c8e-513c-4853-925f-727c37a017c6.png">  
  
## Hur Arkiv DIgital kopplar kyrkbok till karta
   
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/14206509/218426955-95bfdf74-3fa1-4e1e-b952-1207d756555b.png">
