### ISSUE TITLE
Bugg: Några IIIF collections svarar med HTTP 500

### ISSUE THREAD

**Issue by Abbe98** [Riksarkivet/dataplattform#6]
- https://lbiiif.riksarkivet.se/collection/arkiv/fylB2msYXY3DYJh8mkA040
 - https://lbiiif.riksarkivet.se/collection/arkiv/yYxsqjlT62D2RzgXT78Ol7

**Comment by nilsw-ra** [comment]
Undersökning pågår!

**Comment by nilsw-ra** [comment]
Felet är rättat, får återkomma om när åtgärden kan gå i drift.

**Comment by nilsw-ra** [comment]
Åtgärdat i version driftsatt 20221006
