### ISSUE TITLE
IIIF Manifest har olika etiketter på olika platser i RDF-grafen

### ISSUE THREAD

**Issue by Abbe98** [Riksarkivet/dataplattform#8]
Nedan finns ett exempel på hur Collection nivån skiljer sig ifrån manifest nivån men problemet är systematiskt.

https://lbiiif.riksarkivet.se/collection/arkiv/TJkFcljeTasiqC1rTgCU30

```turtle
<https://lbiiif.riksarkivet.se/arkis!K0024239/manifest>
  a <http://iiif.io/api/presentation/3#Manifest> ;
  rdfs:label "0001 1. [Stockholm.]"@sv .
```

https://lbiiif.riksarkivet.se/arkis!K0024239/manifest

```turtle
<https://lbiiif.riksarkivet.se/arkis!K0024239/manifest>
  a <http://iiif.io/api/presentation/3#Manifest> ;
  rdfs:label "Handritade Kartverk, Band 11: Svenska planteboken (Örnehufvud) , SE/KrA/0414/0011/0001 (162-?-163-?)"@sv .
```

Problem kan sedan uppstå när man indexerar dessa tillsammans och får två rdfs:label utan vidare kontext. Det är också lite konstigt i vissa IIIF gränssnitt där etiketter används och kan skilja sig åt på olika ställen i gränssnittet.

**Comment by nilsw-ra** [comment]
Detta är ju inkonsekvent, manifest-referensen i collection får label från den aktuella volymen, medan label i själva manifestet byggs upp av arkivets och seriens titel + referenskod + datering. Vi får ta en diskussion om en eller båda ska ändras.
